### ISSUE TITLE
On android emulator does not detect the fingerprint.

### ISSUE THREAD

**Issue by danieldonev** [NiklasMerz/cordova-plugin-fingerprint-aio#10]
I am using android emulator with API-23, 
this is my code:

```
 FingerprintAIO.isAvailable().then(() => {
        FingerprintAIO.show({
          clientId: 'Title',
          clientSecret: '1234'
        }).then((result: any) => {
          console.log(result)
        }).catch((error) => {
          console.error("1", error) // HERE '1, Fingerprint authentication not available'
        });
      }).catch((error) => {
          console.error("2", error)
      });
```

So even if I already have the check if "isAvailabe", in the "show" catch I get "1, Fingerprint authentication not available"

**Comment by NiklasMerz** [comment]
In my quick test fingerprint authentication worked in the emulator after setting it up through the settings.
I opened the settings app and added a fake fingerprint. After that fingerprint authentication was available in my demo app. I am closing this issue now. Feel free to open it again of you have you any further questions.

**Comment by danieldonev** [comment]
Hello,
Thank you for the quick response,
Apparently my issue was related to #9, because when I updated my version with the one currently on the master branch, it warn me that the fingerprint is not available.
