### ISSUE TITLE
Catch errors list

### ISSUE THREAD

**Issue by ronaiza-cardoso** [NiklasMerz/cordova-plugin-fingerprint-aio#102]
## Description 

* What did you do? 
 - KNOW ERRORS AFTER FINGER DIALOG IS SHOW
* What did happen? 
- finger show dialog but when we have some error the result is not documented
* What did you expect to happen?
 - documented list errors
              if (e === 'Error: Optional(\'Biometry is locked out.\')') {
                  this.util.showToast('Digital bloqueada, favor entrar com login e senha!');
                } else if (e === 'Error: Optional(\'Canceled by user.\')' || e === 'Cancelled') {
                  this.util.showToast('Entre com login e senha!');
                } else if (e === 'Error: Optional(\'Application retry limit exceeded.\')') {
                  this.util.showToast('Limite de tentativas excedido, por favor, entre com login e senha!');
                }
* Type of issue (bug, feature request)
bug

## Environment

* Plugin version
cordova-plugin-fingerprint-aio:  ^1.3.4
* Build environment (```cordova info```)
Node version: v6.11.2

Cordova version: 8.0.0

* ```cordova platform ls```
Installed platforms:
  android 6.3.0
  ios 4.4.0

**Comment by NiklasMerz** [comment]
Thanks for suggesting that. Yes you right there should be some kinde of documentation. But the errors you are catching are Android specific. iOS throws less errors.

**Comment by NiklasMerz** [comment]
I am closing this issue, because it is inactive for some time. If you still have this problem, feel free to contact developers on [Gitter](https://gitter.im/cordova-plugin-fingerprint-aio).

Thank you
