### ISSUE TITLE
Plugin fails silently when no fingerprints of the user stored on the phone

### ISSUE THREAD

**Issue by Muzietto** [NiklasMerz/cordova-plugin-fingerprint-aio#109]
If the user has not stored any fingerprint on an Android phone, the `isAvailable` check fails silently.
The result object of the fingerprint-auth plugin features an `hasEnrolledFingerprints` member.
Such detail is nowhere to be found in the documentation of this plugin.
Verified on a Google Pixel 2 phone.

**Comment by NiklasMerz** [comment]
This should be done with #131
