### ISSUE TITLE
Passcode fallback not showed on iOS 10 and up

### ISSUE THREAD

**Issue by RobinGiel** [NiklasMerz/cordova-plugin-fingerprint-aio#113]
## Description

* What did you do? 
     -> Fail 5 times fingeprint
* What did happen?
     -> nothing
* What did you expect to happen?
     -> fallback passcode showed

On iOS 9 it's working

## Environment

* Plugin version: 1.4.0-0
* Build environment: ios 10 and up

**Comment by NiklasMerz** [comment]
Did you test this with the non RC version? Did you set a fallback text?

**Comment by RobinGiel** [comment]
Yes I did test with the non RC version, and I also set the fallback test. 

I want to achieve the same behavior when I'm using iOS9:

When the fingerprint(TouchID) fails and goes to the fallback (passcode)  after success it still asks the user the authenticate with fingerprint and not directly authenticate only by using the passcode. 

On iOS 10 and up after the fallback (passcode) it directly authenticate the user without asking again to authenticate using TouchID again (this is not the accepted behavior).

**Comment by NiklasMerz** [comment]
To me the iOS 10 and up behavior sounds correct. That´s what I expect from the fallback code. I want to use the fallback for login. If I would not want to use the code I would set `disableBackup `to **true**.

**Comment by gdorbes** [comment]
I have the same issue: Passcode fallback is not displayed when faceId fails even when localizedFallbackTitle and localizedReason are set => Loop in FaceID or TouchID.

## Environment
- plugin: 1.5.0
- disableBackup: false
- ios: 12

Thanks

**Comment by NiklasMerz** [comment]
I am closing this issue. If it is still relevant with the current version please open a new one with up-to-date information.
