### ISSUE TITLE
better return messages from show

### ISSUE THREAD

**Issue by rosstimothy** [NiklasMerz/cordova-plugin-fingerprint-aio#114]
### Feature Request
Android and iOS return very different values and formats for success/errors

#### Feature Description
Some examples of return values that I have seen:
- iOS
    'Success';
    'Error: Optional(\\\"Canceled by user.\\\")';
    'Error: Optional(\\"Misbehaving caller PID:10565 has made too many authentication requests.\\")';
- Android 
   {"withFingerprint":"Sjyn1f1QOg0dufKHaN9R4g==\n"}
   {"withPassword":true}
   'Cancelled';

This formatting makes it harder to parse return values. Perhaps a unified json syntax could be used?

Some documentation would be delightful as well.

**Comment by NiklasMerz** [comment]
Good point. Maybe we should use some kind of success and error codes. So you have number code and message and you can use the number to parse in your app.

**Comment by RobinGiel** [comment]
This would be useful for the `isAvailable()` method as well. In case an error is returned, it would be great to know more, i.e. if the device is Touch/FaceID ready even though it is locked.

**Comment by NiklasMerz** [comment]
With #131 this should really be done. Maybe we could include some status code for programmatic checking.

**Comment by NiklasMerz** [comment]
Should also be done with #173
