### ISSUE TITLE
Fingerprint is not available under global object

### ISSUE THREAD

**Issue by hariramnandagopal** [NiklasMerz/cordova-plugin-fingerprint-aio#117]
### Fingerprint is not available under global object

Thanks for the plugin.

## Description

* Trying to implement Touch / Face ID.
* Fingerprint is not available.
* Expected to have Fingerprint under window object.

## Environment

* Plugin version - 1.3.8.
* iPhone OS - 12 beta [16A5366a]
* Xcode 10.0 beta - Build version [10L232m].
* Node version: v8.9.3.
* Cordova version: 8.0.0.

Same plugin works fine for Android and Fingerprint object is regsitered under window object.

iOS Screenshot [No Fingerprint Available]

![screen shot 2018-09-05 at 11 01 12 am](https://user-images.githubusercontent.com/10302158/45065234-630ee300-b0fb-11e8-95f9-1ec93016a4d2.png)

Android Screenshot [Fingerprint Available]

![fingerprint_android](https://user-images.githubusercontent.com/10302158/45065260-8043b180-b0fb-11e8-98bd-7e9e4b325db6.PNG)

Please let me know if you need any more info from my end.

**Comment by NiklasMerz** [comment]
That is strange. Did you test other iOS and Xcode version. Maybe you could removing the ios platform and adding it again.

**Comment by hariramnandagopal** [comment]
Thanks for the reply.

Please close this issue. Working as expected after platform reinstall. 

Any plans to extend the face id support for Android devices?

**Comment by NiklasMerz** [comment]
I am not aware of a standard Android API for login with face. Maybe some time in the future.
