### ISSUE TITLE
Obtain a credential, code, or id from a fingerprint

### ISSUE THREAD

**Issue by diegoestacho999** [NiklasMerz/cordova-plugin-fingerprint-aio#118]
Good morning everyone, from what I read about this fingerprint function, it stores biometrics in the device through a mathematical operation, and encrypts this for security reasons.
But I'd like to request it, or even if someone else has used something like that. One way to get a return is this, an id, the code of a particular fingerprint.

Because ?
Currently, I'm developing an application that consists of controlling employee's point card via mobile phone using this fingerprint feature. But I was stuck, unable to compare if user 01 is logging in with his own digital, for example.
I insist on this by the following, at some point there may be fraud in the application and one user making the point to the other.

Why Reinforcement?
Currently we also have applications like, banco do brasil and itaú that provide this same service for authentication of its users in the application. But reading today, I discovered that in itaú, for example, there is no negotiation for this. Let's suppose that I and another person use the same phone, and only this person has the bank account in itaú, but we both have biometrics registered in the device. Both I and this person have access to the bank account, which is simply unsafe.

Well, I come here to ask the most experienced if there is the possibility of obtaining some information of return, something that we can do the comparative of the biometrics, a code, or anything that exists. I work with Ionic.

Thank you in advance, and any help or information will be welcome.

**Comment by NiklasMerz** [comment]
Thank you for the suggestion for this feature and the good explanation.  As far as I know this is not possible on iOS. On Android this is done in the original plugin https://github.com/mjwheatley/cordova-plugin-android-fingerprint-auth, on which this plugin is based on. We removed the hash at some point, if I remember it correctly. 

Please have a look at the other plugin, too. If it works there you could use it or create a PR for this plugin. Currently I don´t have much time doing development, but the Android side needs some work. I can image that your suggested feature could be really useful. Feel free to post any comments or pull requests.

I looking forward to your feedback.

**Comment by CedricReichenbach** [comment]
As [mentioned on a different issue](https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/issues/186#issuecomment-553773129), this could fill in the missing piece for a truly secure authentication chain.

**Comment by NiklasMerz** [comment]
Yes @CedricReichenbach like you pointed out https://github.com/sjhoeksma/cordova-plugin-keychain-touch-id is probably the way to go if you need this feature.

I will leave the other issue open. If someone wants to add this. It is currently not on my radar.
