### ISSUE TITLE
Does this plugin supports the fallback for pin log in. I mean if the devices don't support either touch ID/ Face ID does it able to fallback to pin ?

### ISSUE THREAD

**Issue by benjamin-b** [NiklasMerz/cordova-plugin-fingerprint-aio#119]
#### Feature Description
Does this plugin supports the fallback for pin log in. I mean if the devices don't support either touch ID/ Face ID does it able to fallback to pin ?

**Comment by pserna95** [comment]
I'm not sure if this work as expected. If the android version is lower than 23 and your device doesn't have touch ID, the plugin doesn't show the dialog to introduce your lock pin.

Can you take a look at this?

**Comment by NiklasMerz** [comment]
Whithout the the fingeprint API this plugin wont work. You must check availability first.
