### ISSUE TITLE
Cordova plugin version is not updated

### ISSUE THREAD

**Issue by yzn002** [NiklasMerz/cordova-plugin-fingerprint-aio#12]
Hi,

After installing the plugin using `ionic plugin add cordova-plugin-fingerprint-aio --save`, config.xml will show that you installed version 0.6.0 not 1.0.1.

Thanks.

**Comment by NiklasMerz** [comment]
Thank you very much for reporting this. I forgot to change the version in the plugin.xml file. The new version 1.0.2 is now available.
