### ISSUE TITLE
Get errors when try build for Ionic IOS

### ISSUE THREAD

**Issue by muhammadomais** [NiklasMerz/cordova-plugin-fingerprint-aio#121]
## Description

* What did you do?
```ionic cordova build ios```

* What did happen?

/Users/momais01/Desktop/ionic/ionicpro/myblue/platforms/ios/MyApp/Plugins/cordova-plugin-fingerprint-aio/Fingerprint.swift:6:5: error: expected declaration

    fileprivate var policy:LAPolicy!

    ^

/Users/momais01/Desktop/ionic/ionicpro/myblue/platforms/ios/MyApp/Plugins/cordova-plugin-fingerprint-aio/Fingerprint.swift:6:16: error: consecutive declarations on a line must be separated by ';'

    fileprivate var policy:LAPolicy!

               ^

               ;

/Users/momais01/Desktop/ionic/ionicpro/myblue/platforms/ios/MyApp/Plugins/cordova-plugin-fingerprint-aio/Fingerprint.swift:8:22: warning: extraneous '_' in parameter: 'command' has no keyword argument name

    func isAvailable(_ command: CDVInvokedUrlCommand){

                     ^~

                     

/Users/momais01/Desktop/ionic/ionicpro/myblue/platforms/ios/MyApp/Plugins/cordova-plugin-fingerprint-aio/Fingerprint.swift:34:23: warning: extraneous '_' in parameter: 'command' has no keyword argument name

    func authenticate(_ command: CDVInvokedUrlCommand){

                      ^~

                      

/Users/momais01/Desktop/ionic/ionicpro/myblue/platforms/ios/MyApp/Plugins/cordova-plugin-fingerprint-aio/Fingerprint.swift:77:15: warning: unnecessary check for 'iOS'; minimum deployment target ensures guard will always be true

        guard #available(iOS 9.0, *) else {

              ^

/Users/momais01/Desktop/ionic/ionicpro/myblue/platforms/ios/MyApp/Plugins/cordova-plugin-fingerprint-aio/Fingerprint.swift:15:43: error: incorrect argument label in call (have 'status:messageAs:', expected 'status:messageAsString:')

        var pluginResult = CDVPluginResult(status: CDVCommandStatus_ERROR, messageAs: "Not available");

                                          ^                                ~~~~~~~~~

                                                                           messageAsString

/Users/momais01/Desktop/ionic/ionicpro/myblue/platforms/ios/MyApp/Plugins/cordova-plugin-fingerprint-aio/Fingerprint.swift:18:24: error: value of type 'LAContext' has no member 'biometryType'

                switch(authenticationContext.biometryType) {

                       ^~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~

/Users/momais01/Desktop/ionic/ionicpro/myblue/platforms/ios/MyApp/Plugins/cordova-plugin-fingerprint-aio/Fingerprint.swift:36:43: error: incorrect argument label in call (have 'status:messageAs:', expected 'status:messageAsString:')

        var pluginResult = CDVPluginResult(status: CDVCommandStatus_ERROR, messageAs: "Something went wrong");

                                          ^                                ~~~~~~~~~

                                                                           messageAsString

/Users/momais01/Desktop/ionic/ionicpro/myblue/platforms/ios/MyApp/Plugins/cordova-plugin-fingerprint-aio/Fingerprint.swift:43:27: error: type 'LAPolicy!' has no member 'deviceOwnerAuthenticationWithBiometrics'

                policy = .deviceOwnerAuthenticationWithBiometrics;

                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/Users/momais01/Desktop/ionic/ionicpro/myblue/platforms/ios/MyApp/Plugins/cordova-plugin-fingerprint-aio/Fingerprint.swift:78:23: error: type 'LAPolicy!' has no member 'deviceOwnerAuthenticationWithBiometrics'

            policy = .deviceOwnerAuthenticationWithBiometrics

                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/Users/momais01/Desktop/ionic/ionicpro/myblue/platforms/ios/MyApp/Plugins/cordova-plugin-fingerprint-aio/Fingerprint.swift:82:19: error: type 'LAPolicy!' has no member 'deviceOwnerAuthentication'

        policy = .deviceOwnerAuthentication

                  ^~~~~~~~~~~~~~~~~~~~~~~~~

** BUILD FAILED **

**Comment by NiklasMerz** [comment]
Please open the project in Xcode and check the Swift version. Which version of the plugin do you use?

**Comment by muhammadomais** [comment]
When i run following command in the terminal
`xcrun swift -version`
I get following information
Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.31)
Target: x86_64-apple-macosx10.9

**Comment by NiklasMerz** [comment]
Please open the project in Xcode and set the version to 3.2

**Comment by muhammadomais** [comment]
I looked in the build setting Swift version is 3.2

**Comment by muhammadomais** [comment]
Build Settings
[https://drive.google.com/open?id=1YmXkDC-rKutBPW5vujr4sc2xWzXpYYOT](url)
File showing errors
[https://drive.google.com/open?id=1TH0IGBKvWvDePACH1Qi24LBj7okx-gnf](url)

**Comment by NiklasMerz** [comment]
For which iOS version are you building? Do you use the latest Xcode?

**Comment by muhammadomais** [comment]
I am building for 9 and up and i am using the latest Xcode

**Comment by NiklasMerz** [comment]
The plugin only works on iOS 11. Previous versions worked on 10 I think.

**Comment by muhammadomais** [comment]
I changed the mini deployment version to 11 and Swift version to 3.2. Still having the same problem. Error pointing to Fingereprint.swift file.
[File showing errors](https://drive.google.com/open?id=1TH0IGBKvWvDePACH1Qi24LBj7okx-gnf)

**Comment by NiklasMerz** [comment]
Is this still a problem?

**Comment by onfire** [comment]
@muhammadomais I am getting the same problem, did you resolve it in the end?

@NiklasMerz I am building for iOS 11 but getting the same issue as above when trying to build using `ionic cordova build ios`:

```
 var policy:LAPolicy = .deviceOwnerAuthentication;
                               ^
/Users/admin/Sites/giftstation-app-v2/platforms/ios/Giftstation/Plugins/cordova-plugin-fingerprint-aio/Fingerprint.swift:44:32: note: add 'if #available' version check
        var policy:LAPolicy = .deviceOwnerAuthentication;
                               ^
/Users/admin/Sites/giftstation-app-v2/platforms/ios/Giftstation/Plugins/cordova-plugin-fingerprint-aio/Fingerprint.swift:40:10: note: add @available attribute to enclosing instance method
    func authenticate(_ command: CDVInvokedUrlCommand){
         ^
/Users/admin/Sites/giftstation-app-v2/platforms/ios/Giftstation/Plugins/cordova-plugin-fingerprint-aio/Fingerprint.swift:4:26: note: add @available attribute to enclosing class
@objc(Fingerprint) class Fingerprint : CDVPlugin {
```
