### ISSUE TITLE
Enter password fallback doesn't work when fingerprint fails

### ISSUE THREAD

**Issue by rpanadero** [NiklasMerz/cordova-plugin-fingerprint-aio#123]
## Description

I have detected an issue on iOS with the plugin in version 1.4.0 which didn't happen in the version 1.3.8. The problem is that when the user badly uses the fingerprint, it appears a new option called 'Enter password' which doesn't respond  if you press on it, the popup is inmediately closed and this error is dispatched: "Error: Optional(\"Fallback authentication mechanism selected.\")"

I have been analyzing the issue looking at the plugin code and it seems that the policy used in the 'authenticate' method is wrong. The broken change was introduce in this commit: https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/commit/f14841d3f8b3c114efa723678ef7cb90fdd844c3

Please, have a look to my pull request because I have tested my changes in several iOS devices (iPhone 6 and iPhone 6S) and the fallback ("Enter password") is working now. https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/pull/124

By the way, just for being clear, my device is properly configured with Touch Id and it works successfully when I use it by this plugin. The only problem is the fallback way.

Overview to reproduce the issue:

1 - Configure Touch Id for your iOS device
2 - Invoke `Fingerprint.show` method to show a popup that permits biometric authentication
```
Fingerprint.show({
      clientId: "Fingerprint-Demo",
      clientSecret: "password" //Only necessary for Android
}, successCallback, errorCallback);

function successCallback(){
  alert("Authentication successfull");
}

function errorCallback(err){
  alert("Authentication invalid " + err);
}
```
3 - Fail biometric authentication, for instance by using a wrong finger. It will appear 'Enter password' option
4 - Press on 'Enter password' option and nothing will happen.

Expected behaviour: Passcode view must be displayed

If you have doubts abouts my fix, please feel free to write me.

## Environment

* Plugin version: 1.4.0
* Node version: v10.11.0
* Cordova version: 8.0.0
* Xcode 9.4.1

**Comment by NiklasMerz** [comment]
Thank you very much. This is an example of a perfect issue. Thanks for the description and pull request. Your change definitely makes the code better to understand. All your tests worked on iOS 11 and 12? Did you try `npm test ios`?

I will merge #124 after I had time to do quick test on device but I looks good to me. 🥇
