### ISSUE TITLE
Can we set "USE BACKUP" as optional?

### ISSUE THREAD

**Issue by sabariferin** [NiklasMerz/cordova-plugin-fingerprint-aio#13]
@NiklasMerz In the android version, can we set "USE BACKUP" as optional?

Thanks,

**Comment by NiklasMerz** [comment]
Yes you could try calling "show" like this:

```javascript
Fingerprint.show({
      clientId: "Fingerprint-Demo",
      clientSecret: "password",
      disableBackup: true
    }, successCallback, errorCallback);
```
If this works for you I will add this to README.

**Comment by sabariferin** [comment]
Already I have tried the above option, but not working. There is no field for "disableBackup" in "FingerprintOptions" interface. 

SS: https://www.screencast.com/t/BofGMdElN

**Comment by NiklasMerz** [comment]
Are you using Typescript and Ionic Native?

**Comment by sabariferin** [comment]
Yes

**Comment by NiklasMerz** [comment]
Ok this option should be added to the interface in Ionic Native. Try to find the Interface in your project and add this property.

**Comment by sabariferin** [comment]
Ok.

**Comment by NiklasMerz** [comment]
See PR #14
