### ISSUE TITLE
Plugin should have different error messages for when fingerprint hardware is available vs fingerprint not being registered on device.

### ISSUE THREAD

**Issue by pomgrot** [NiklasMerz/cordova-plugin-fingerprint-aio#130]
Greetings,

I am working for a bank and am considering using your plugin for our banking app. There is a problem that's stopping us from continuing, though, and something that could be beneficial to others.

Our security audit has exposed the need to determine whether fingerprint hardware is available versus whether a fingerprint has been registered with device. The distinction between these two things is important as the presence of fingerprint hardware ensures a certain level of device security that we want to know about.

The failure callback on Fingerprint.isAvailable gives you an identical error message in both cases (tested on Samsung S8). Our developers here have limited native development, hence why we are using Cordova, and we'd rather not take the deep dive to make our own plugin when such a small fix could solve our issues. What do you think?

**Comment by NiklasMerz** [comment]
This is a good idea. I don't know the exact details of the Android API right now but this should be a small change. Is this just an issue on Android?

Would you like to have a look? I am happy to review a PR for this feature. I may have a look myself when I find time.

**Comment by pomgrot** [comment]
Sorry to sound selfish, but we're a bunch of TFS & .NET scrubs here, so this entire world of github & java is unfamiliar territory and we're not tooled to work with it.
I've looked at the code and I think that if you change line #255 in Fingerprint.java from this:

mCallbackContext.error("Fingerprint authentication not ready");

to this:

if (mFingerPrintManager.isHardwareDetected() && !mFingerPrintManager.hasEnrolledFingerprints()) {
    mCallbackContext.error("Fingerprint authentication not ready");
} else {
    mCallbackContext.error("Fingerprint authentication not available");
}

Then that would solve the issue.
The phrasing of those error messages is, I believe, appropriate, as "not ready" implicates that fingerprint is possible but just not ready to be utilised and "not available" indicates that it's not possible to use fingerprint on the device as there is no hardware.

Would you be able to make that change for us? It would be greatly appreciated.

**Comment by NiklasMerz** [comment]
No problem. I would love to help you make your first pull request on Github. There are some great resources out there like  https://thenewstack.io/getting-legit-with-git-and-github-your-first-pull-request/  or https://lab.github.com/. I think knowing the basics about Github is a good skill to have.

Anyways did you try that change locally. For a Quick test you can temporarily change these lines in your projects platforms/Android folder and see if it works.

If you don't create a pull request I can try this myself soon, but would love to review your change :-)

**Comment by pomgrot** [comment]
It's good to up-skill. Thank you for that tutorial.

I have (hopefully correctly) created a pull-request with the change from my comment in it.

**Comment by pomgrot** [comment]
Additional to the hopeful acceptance of the pull request, can you elucidate on how the NPM package gets updated - is that a separate process?

The final version of our app is built using the phonegap build service - so we don't include plugins in the zip package we upload to that service, we include a line in the config and the build service gets it from NPM, like so: <plugin name="cordova-plugin-fingerprint-aio"/>

I presume that publishing to NPM is a separate process? Or is it automatic. Sorry for the question bombardment from my ignorance.

**Comment by NiklasMerz** [comment]
Thank you very much @pomgrot . I am happy to answer any questions and support your first contribution of course :-)

Your first pull request looks perfect. I will run some tests and then merge it.

Regarding the new NPM release: I will create a new release locally and push it with your changes to NPM. Probably this will be a RC (release candidate) release for now.

**I will keep you updated here and post instructions to use it, soon.**

**Comment by NiklasMerz** [comment]
@pomgrot I merged your PR and published it as version 1.5.0 You did a great job :1st_place_medal: 

You can add it to your project via Cordova CLI `cordova plugin add cordova-plugin-fingerprint-aio`
You next phonegap build should fetch this version, too.

Again. Thank you very much.

**Comment by pomgrot** [comment]
@NiklasMerz Thank you for the prompt help and feedback.
