### ISSUE TITLE
How to authenticate against an external service?

### ISSUE THREAD

**Issue by FarhadG** [NiklasMerz/cordova-plugin-fingerprint-aio#133]
Thanks for the great module!

I couldn't find in the documentation how one would go about authenticating a user against an API service that requires a username/password. Is there a particular approach or process that I'm missing here? Thanks, in advance, for the help!

**Comment by NiklasMerz** [comment]
Please have a look at #45 . Especially this [feature](https://android-developers.googleblog.com/2015/10/new-in-android-samples-authenticating.html)

It is not implemented in this plugin, yet.

**Comment by FarhadG** [comment]
Thanks for the quick response, @NiklasMerz! What if I were to go with the following approach:

1) Have user provide username/password to external services and store them on the device via (https://github.com/Crypho/cordova-plugin-secure-storage)
2) Whenever they come back to the application, I can retrieve the credentials from storage and authenticate with external services

Do you see any issues with this? How does this approach differ from remote server authentication?

Sorry, it's been hard to find details around this stuff on the web. Thanks, in advance, for your assistance!

**Comment by NiklasMerz** [comment]
@FarhadG You are right. I have done this myself too. This does work on iOS and Android and can be a valid approach if it is ok for you to store credentials on the phone. The secure storage plugin should be good for this.

I am closing this as this is more a question for implementing than a bug or feature request.
