### ISSUE TITLE
In iOS phonegap build is error

### ISSUE THREAD

**Issue by kalaiprakash93** [NiklasMerz/cordova-plugin-fingerprint-aio#140]
After added this plugin phonegap build is not successful.Please help me out of this.
I have attached  my config.xml file code.and errors.
![capture6](https://user-images.githubusercontent.com/19145824/51295866-95ccce80-1a3f-11e9-9fbc-6725772822c2.PNG)

LOG URL : https://build.phonegap.com/apps/3435374/logs/ios/build/

`<?xml version='1.0' encoding='utf-8'?>
<widget id="com.phonegap.helloworld" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>Device Features</name>
    <description>
        A basic Framework7 template for PhoneGap.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
	<preference name="phonegap-version" value="cli-8.0.0" />
        <preference name="android-minSdkVersion" value="21" />
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <preference name="UseSwiftLanguageVersion" value="3.2" />
        <preference name="BackupWebStorage" value="none" />
    </platform>
    <preference name="DisallowOverscroll" value="true" />
    <plugin name="cordova-plugin-whitelist" spec="~1.2.0" />
    <plugin name="cordova-plugin-console" spec="~1.0.1" />
    <plugin name="cordova-plugin-statusbar" spec="~1.0.1" />
    <plugin name="cordova-plugin-device" spec="~2.0.2" />
    <plugin name="cordova-plugin-geolocation" source="npm" />
    <plugin name="cordova-plugin-fingerprint-aio" spec="~1.5.0" >
        <variable name="FACEID_USAGE_DESCRIPTION" value="Unlock when resuming" />
    </plugin>
</widget>`

**Comment by NiklasMerz** [comment]
I never used phonegap build and I don´t know if it is compatibile.

Could you please post the log? The link does not work without authentication.

**Comment by fasjunior** [comment]
I'm having the same problem, compile for android but not for ios. I think Phonegap Build does not support the Swift language, other plugins that use this language are having the same problem: https://forums.adobe.com/message/10430720#10430720

Log:

**=== BUILD TARGET Dominus OF PROJECT Dominus WITH CONFIGURATION Release ===

Check dependencies
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.

** ARCHIVE FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/private/project/cordova/build-release.xcconfig,-workspace,Dominus.xcworkspace,-scheme,Dominus,-configuration,Release,-destination,generic/platform=iOS,-archivePath,Dominus.xcarchive,archive,CONFIGURATION_BUILD_DIR=/private/project/build/device,SHARED_PRECOMPS_DIR=/private/project/build/sharedpch,-UseModernBuildSystem=0**

**Comment by NiklasMerz** [comment]
Did you try `<preference name="UseSwiftLanguageVersion" value="3.0" />` in you config.xml file?

This could help. Other swift versions may work, too.

**Comment by fasjunior** [comment]
Yes, but not working. I solved it in a different way, I include a bridge header in plugin.xml:

```
<platform name="ios">
...
<header-file src="src/ios/Bridging-Header.h" />
...
</platform>
```

And the **Bridging-Header.h** file consists of:

`//
//  Use this file to import your target's public headers that you would like to expose to Swift.
//

#import <Cordova/CDV.h>`

I made a fork of your project in mine and changed it: https://github.com/fasjunior/cordova-plugin-fingerprint-aio.git

**Comment by NiklasMerz** [comment]
Would you like to create a pull request? I could test this and the header shouldn´t hurt.

**Comment by fasjunior** [comment]
Ok
