### ISSUE TITLE
disable fingerprint after first use

### ISSUE THREAD

**Issue by gurnard123** [NiklasMerz/cordova-plugin-fingerprint-aio#143]
#### Feature Description
This might already be possible. Basically I want to disable the fingerprint for my app. So a user initially logs in with fingerprint so then it is registered with that clientID I presume on the device.
Is there anyway to de-register that clientID on the device or disable it for a user. The reasoning is that users want to stop using fingerprint or they want to register a different finger for instance.
Is this currently possible?  Or with another plugin maybe?

**Comment by NiklasMerz** [comment]
I don´t understand the question exactly. But I think you can do all of that in your app. Just show the fingerprint dialog when you want it to use. If a user changes the fingerprints on Android it is disabled automatically right now.

**Comment by gurnard123** [comment]
I have an issue that is reported by a user that when if (on Android) you modify the system’s fingerprint (ie. remove it first, than register it again) the mobile app keeps asking for a fingerprint but it doesn’t work anymore. I think this is because the fingerprint’s ID is has changed and the app is still expecting the old ID.

So  I see this as more of a bug then if you think it should function.  You provide no option in the api to re-register and I cannot detect if it has been changed on the OS. Or can I?

**Comment by gurnard123** [comment]
The problem is that FingerAIO throws an exception. This is how to reproduce:

- register a fingerprint on your device
- open app using fingerAIO (fingerprint works correctly)
- close the app
- remove all registered fingerprints
- open the app using fingerAIO.
isAvailable() is returning OK which is good but a call to show(options) throws an invalidAlgorithmParameterException, detailed below.

So it looks like a bug to me. There is a registered fingerprint with the system but it is not the same as was used when the original show() was called.

These are the options but I don't know much about these as I can't find any documentation back from when I wrote this.

{
            clientId: 'myApp',
            clientSecret: 'someClientSecret',
            disableBackup: true
        }

Failed to create key: InvalidAlgorithmParameterException: java.security.InvalidAlgorithmParameterException: java.lang.IllegalStateException: At least one fingerprint must be enrolled to create keys requiring user authentication for every use", source: file:///android_asset/www/build/main.js (30951)h

**Comment by gurnard123** [comment]
OK it appears to work if I do not specify disableBackup in the options passed to show. 
I not remember where I got this option from as it was over a year ago that I developed this app.
I will test further to ensure that is the fix.

**Comment by gurnard123** [comment]
It appears that not passing disableBackup as part of the options to the show() function fixes the issue.

**Comment by NiklasMerz** [comment]
Seems to be resolved
