### ISSUE TITLE
 Language and change of messages

### ISSUE THREAD

**Issue by camila-frangp** [NiklasMerz/cordova-plugin-fingerprint-aio#146]
Is possible to change the messages of the plugin ... Sorry I am new to this and I have been investigating for some time and I still can not find a solution

**Comment by NiklasMerz** [comment]
If you just need to change the message on iOS you can use `localizedReason` as a parameter for `show({localizedReason: 'TEXT'})`. This should change the message in the dialog. For Android this plugin needs translations like [these ](https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/blob/master/res/android/values-es/fpauth-strings.xml). But Spanish should be there already.

If it works please close the issue, if not let us know.
