### ISSUE TITLE
Fingerprint Auth receives error when locking phone causing a fallback to Backup dialog

### ISSUE THREAD

**Issue by Smashman** [NiklasMerz/cordova-plugin-fingerprint-aio#148]
## Description
On Pixel 2 XL, if the Fingerprint Auth is showing when locking the phone, we receive a `FINGERPRINT_ERROR_CANCELED`, which causes the auth to fallback to the backup flow immediately.
When unlocking the phone, the backup flow is shown, which is rather confusing and might cause a user to be mistake the window for phone unlock.

## Repro
* Start an auth dialog
* Lock the Pixel 2 XL
• Unlock the phone

### Expected result
* Auth dialog is still there when returning from unlocking the phone

### Actual result
* Auth flow has gone to backup flow and presents immediately after unlocking phone.

## Environment

* Plugin version: 1.3.6
* Android 9
* Pixel 2 XL

**Comment by NiklasMerz** [comment]
Closed since #179 fixed this issue. Thank you for contributing!
