### ISSUE TITLE
Update to Swift 4 for XCode 10.2

### ISSUE THREAD

**Issue by cristobal-tudela-ruiz** [NiklasMerz/cordova-plugin-fingerprint-aio#150]
### Feature Request
Hi, with the upgrade to XCode 10.2 is requerid Swift 4. It will be discontinued Swift 3. 

My project use Ionic 3.

**Comment by wesley-devmuis** [comment]
Updating an ionic project with this plugin to Swift 4 works without any alterations, I've tried this myself. What's the problem?

**Comment by cristobal-tudela-ruiz** [comment]
Actualmente el plugin que utiliza Ionic 3 trabaja con Swift 3 y con la nueva version de XCode 10.2 sera de forma obligatoria migrar a swift 4.

**Comment by NiklasMerz** [comment]
I don´t speak Spanish but did you try setting `<preference name="UseSwiftLanguageVersion" value="4.0" />` in your `config.xml`? This should help and I usually set those versions in Xcode before building in Xcode.

**Comment by lunedam-git** [comment]
Perhaps you are not building your project from scratch so as well as setting `<preference name="UseSwiftLanguageVersion" value="4.0" />` in your `config.xml` you also need to set the 'Swift Language Version' to 'Swift 4' in the 'Swift Compiler - Language' section of the Build Settings of your Xcode project...

**Comment by NiklasMerz** [comment]
@lunedam-git Yes that is correct. The PR with the updated dependency is now merged.

**Comment by jimbergman** [comment]
@NiklasMerz please update the README for the repo to instruct users to set `<preference name="UseSwiftLanguageVersion" value="4.0" />` in `config.xml` Thanks!

> ... you also need to set the 'Swift Language Version' to 'Swift 4' in the 'Swift Compiler - Language' section of the Build Settings of your Xcode project...
Thank you for posting this @lunedam-git, saved me a bunch of searching.

**Comment by NiklasMerz** [comment]
Thanks @jimbergman Done
