### ISSUE TITLE
Attempt to invoke virtual method 'boolean android.hardware.fingerprint.FingerprintManager.isHardwareDetected()' on a null object reference

### ISSUE THREAD

**Issue by dstefanoska** [NiklasMerz/cordova-plugin-fingerprint-aio#151]
## Description

* What did you do?
I'm installing the app on a TECNO F1 device running Android GO

* What did happen?
When the plugin is added in the constructor it's showing error
`Error: Uncaught (in promise): Attempt to invoke virtual method 'boolean android.hardware.fingerprint.FingerprintManager.isHardwareDetected()' on a null object reference`
in the console.
This issue happens just on that phone from all my testing devices, but note that's the only device that doesn't have a fingerprint sensor which I've tested on.

## Environment
I'm using Ionic 3, cordova-plugin-fingerprint-aio: ~1.6.0 and @ionic-native/fingerprint-aio: "^4.20.0 when I got this issue.
Building in debug mode.

## Notes
If you have any additional question about the issue please ask and I'll try to give as much data as I can.

**Comment by NiklasMerz** [comment]
Thank you for reporting. Possibly Android Go behaves diffrently.

**Comment by spargo-protek** [comment]
The same on Xiaomi 6A
Android 8.1.0 O11019

**Comment by spargo-protek** [comment]
Please add a null check as described here:
https://github.com/omadahealth/LolliPin/issues/195

**Comment by NiklasMerz** [comment]
Please test #179

**Comment by NiklasMerz** [comment]
Probably fixed

**Comment by richardshergold** [comment]
Hi. Just installed the new version and I'm getting the error BIOMETRIC_HARDWARE_NOT_SUPPORTED even though my device (running Android 9) has FACE ID set up?
