### ISSUE TITLE
Conflict with keychain plugin

### ISSUE THREAD

**Issue by NiklasMerz** [NiklasMerz/cordova-plugin-fingerprint-aio#152]
Looks like some icons for Android should be renamed

Transferred from #111:

> I solved this problem by removing this plugin https://ionicframework.com/docs/native/keychain-touch-id/. Somehow these two plugins cannot work together.

It's right!!
Both can't be together, if you try it show this message:

/platforms/android/app/src/main/res/drawable/ic_fingerprint_error.xml" already exists!

Someone, can work with both?
I use keychaintouchid for storage the password.
It works perfectly in iOS, buth not in Android.

Any suggest?

_Originally posted by @JrSagas in https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/issues/111#issuecomment-475309961_

**Comment by giorgiogalassi** [comment]
Hi,

Any news on this?

Regards.

**Comment by NiklasMerz** [comment]
No. I guess one of the plugins has to change the name of the resources.

**Comment by giorgiogalassi** [comment]
> No. I guess one of the plugins has to change the name of the resources.

Ok. Since i kinda need it fixed i'll probably do by my self and send a pull request to you.

How much time do you need to merge?

Regards.

**Comment by Flowrome** [comment]
Hi @NiklasMerz 

as soon the fix is just for the icon i've don a branch to fix the naming.
I can't push it due to permission issues, so i'm requesting you the push permission to another branch to create the pull request.

Have a nice day

Thank you

Romeo Nupieri

**Comment by Flowrome** [comment]
Hi @NiklasMerz 

i've pushed a pull request with the fix.
hope you can consider to make a new release.

Thank you

Have a nice day

Romeo Nupieri

[Pull request](https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/pull/174)
