### ISSUE TITLE
Update cordova-plugin-add-swift-support to get Cordova CLI 9 support

### ISSUE THREAD

**Issue by adamdport** [NiklasMerz/cordova-plugin-fingerprint-aio#153]
### Bug report
Can't run on Cordova CLI 9

## Description
When running Cordova CLI 9, an error is emitted; 

`Executing script found in plugin cordova-plugin-add-swift-support for hook "after_prepare": plugins\cordova-plugin-add-swift-support\add-swift-support.js
Using "requireCordovaModule" to load non-cordova module "glob" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
CordovaError: Using "requireCordovaModule" to load non-cordova module "glob" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.`

[This issue has been resolved by that library](https://github.com/akofman/cordova-plugin-add-swift-support/issues/56) in [2.0.1](https://github.com/akofman/cordova-plugin-add-swift-support/blob/master/CHANGELOG.md). If cordova-plugin-fingerprint-aio updates its dependencies to 2.0.1, the issue should be resolved. Thanks.

## Environment

1.6.0

**Comment by NiklasMerz** [comment]
Thanks for reporting. Do you want to make the pull request for that and do a quick test?

**Comment by JPAlfa** [comment]
I'm still having problem with the cordova-plugin-add-swift-support in v2.0.2 (I tried with 2.0.1 too). Take a look at this [Issue](https://github.com/akofman/cordova-plugin-add-swift-support/issues/69). Am I missing something? I could make a PR there but I don't know the time of response on that repo, and don't know why no one else open an issue about this. I think I'm missing some version or configuration.
