### ISSUE TITLE
Just curious for the status

### ISSUE THREAD

**Issue by grapemix** [NiklasMerz/cordova-plugin-fingerprint-aio#16]
Hi,

Thanks for this interesting plugin.

In ionic's website, this plugin is marked as Beta, so is this plugin ready for production? I can't find any further info anywhere and I can't roadmap in this repo too. The star # and the fork # really make us hesitate.

If this plugin is still in beta, what is the missing piece and when can we expect this plugin to be production ready?

**Comment by NiklasMerz** [comment]
Hello, 

I can't tell you if you should consider this plugin production ready. I created this plugin with the goal to provide a plugin simple to use and integrated into ionic. In my opinion it works well but I did not use it in any production app. I think there are some developers out there who use it and tested it well. I am regularly receiving tickets. The Android implementation is adapted from the plugin linked and the iOS code is rewritten in Swift. Currently there are no real plans for further features but if someone comes up with an idea, it could be integrated. It is possible to detect if fingerprint authentication is available and to perform standard OS authentication. 

I can not guarantee you that this plugin is 100% percent secure but it uses the OS provided SDKs. If you want one plugin for Android and iOS you should give it a try. 

If you have any further questions, don't hesitate to contact me. May I ask you where you have found the beta note?

**Comment by grapemix** [comment]
Thanks for your reply. An active maintainer is a crucial factor for us to choose libs/plugins. In the ionic2 [doc](https://ionicframework.com/docs/native/), if you scroll down in the left hand side panel, you will see the url with the beta icon. You can contact with the ionic team to change this plugin's status. They are pretty friendly. Let us know if you need further info.
