### ISSUE TITLE
[Question] Fingerprint with api and database.

### ISSUE THREAD

**Issue by redplane** [NiklasMerz/cordova-plugin-fingerprint-aio#161]
Hi,

I'm using `cordova-plugin-fingerprint-aio` to do authentication to my app.
This is my application use case:

-- `Front-end`
1. **User** registers an account.
2. **User** sign into application using account which he/she created.
3. **User** scan fingerprint and submit fingerprint data to api.

-- `Back-end`
1. Back-end read the **fingerprint that user submitted** and User information from **access_token**
2. Back-end saves the **fingerprint** with **username** in **database**

What I want is: Next time, if user logs out the application, he/she can use his/her registered fingerprint data to sign into application automatically.

**What I have done**:

- I applied the plugin successfully, authenticated successfully, however, I realize everytime when I get authenticated using **fingerprint**, the results were different. (Please see the image below)

![fingerprint-auth](https://user-images.githubusercontent.com/7974095/57064850-30ed6980-6cfa-11e9-9dcf-b162448caae0.png)

**My question is**: 

- Can we generate anything like **public key** and **private key** from the **fingerprint** we scanned ? If **public-private key pair** is able to be generated, the authentication would be doable.

**Comment by NiklasMerz** [comment]
Hi,

The fingerprint APIs provided by Android and iOS don't return information about the fingerprint. Basically every app I known just uses fingerprint auth locally. This means you should implement your user authentication with normal user+password pairs and fingerprint is an additional option which asks for a fingerprint to pass by the user+password prompt.

I hope this answers you question in some way. Feel free to go to this projects Gitter for further questions.

**Comment by redplane** [comment]
Thank you for your reply.

Now I understand how the `Fingerprint authentication`  works.
By taking a look at some apps using `Fingerprint authentication`, I understands that they save the `username` and `password` in some secured area. When I use my fingerprint, the app will send my stored `username` and `password` to the api again :).

**Comment by NiklasMerz** [comment]
Yes that's basically how you could do that. Make sure that your credentials are stored securely like with https://github.com/Crypho/cordova-plugin-secure-storage
