### ISSUE TITLE
Open pattern lock instead of fingerprint on Android

### ISSUE THREAD

**Issue by DevItAndroidTeam** [NiklasMerz/cordova-plugin-fingerprint-aio#162]
#### Feature Description

This feature is useful if user has only set "PATTERN"  in his/her mobile. Mobile supports fingerprint but user has only set "PATTERN".  In this case , is it possible to open pattern directly?

**Comment by NiklasMerz** [comment]
Thanks for your feature request. Since I am mostly using this plugin for fingerprint in addition to PIN authentication implemented in the app someone else could explore this and make suggestions. Looking forward!

**Comment by bendspoons** [comment]
Hi, a littel late for this question, but if youre not famialiar with native programming you could write your own fallback with a pattern library like this: http://ignitersworld.com/lab/patternLock.html

**Comment by NiklasMerz** [comment]
I think this is out of scope
