### ISSUE TITLE
We would like to get more information in the error callback for isAvailable

### ISSUE THREAD

**Issue by byronaltice** [NiklasMerz/cordova-plugin-fingerprint-aio#166]
### Feature Request

Currently isAvailable returns "Not Available" for every error scenario, regardless of whether this is due to biometry being not available, or the user has denied permissions, etc. 

We would like to get an object in the callback instead of a string, but we don't want to break the current isAvailable().

#### Feature Description

The Object should contain the error code, this could be an integer (-6, -4, etc), or string description, or any way to distinguish the different kinds of errors.

for iOS e.g.:
* user has denied biometric permissions 
* biometry not enrolled
* biometry not available

for android...
* would be undefined since android doesn't return any codes.

We currently have code which changes the parameter type from string to object, but we realize this is not ideal.

We considered making a new method so that isAvailable(success, (string) => ...) works as normal, we could call it verifyBiometric(success, (object) => ... )

What do you think? We can make a pull request and implement however you like.

Thanks for your help.

**Comment by NiklasMerz** [comment]
I like you proposal. Please submit your preffered way as a PR and we can talk about it.
