### ISSUE TITLE
Package size added 70MB to iOS and 70KB to Android!

### ISSUE THREAD

**Issue by WallioApp** [NiklasMerz/cordova-plugin-fingerprint-aio#167]
Hello,

my app was compiling to ~13.5MB on both iOS and Android platforms. After installing this plugin, Android package grew up in size slightly to ~14MB while iOS package ballooned to ~85MB !

Is that normal?
Thanks.

**Comment by NiklasMerz** [comment]
This could be normal. This plugin uses Swift on iOS and it adds the Swift runtime. That's probably the big chunk. Maybe you can try to reduce that size with some build settings in Xcode.

Feel free to post you findings.

**Comment by WallioApp** [comment]
I am using IONIC's AppFlow to build an app and have no access (or clue) to play with Xcode settings...

However, few observations to share:
13.5MB app (without this plugin) produced by Ionic AppFlow becomes 43MB app after Apple processing and when it ready for app store submission.

85MB app (with this plug in) produced by IONIC AppFlow becomes 53MB app after Apple processing and when it is ready for app store submission.

So this plugin adds but not as much as I originally thought. I am curious what Apple does to the app during processing....

**Comment by NiklasMerz** [comment]
While uploading to the App Store Apple does strip some Swift stuff as far as I know.

Thanks for the info.
