### ISSUE TITLE
Unable to build for minSdkVersion< 21

### ISSUE THREAD

**Issue by kunal999** [NiklasMerz/cordova-plugin-fingerprint-aio#17]
Does this plugin allow to build for Android with minSdkVersion 16?
It gives me an error:-
```invalid resource directory name: <project>\platforms\android\build\intermediates\res\merged\debug/drawable-anydpi-v21```

However bumping the minSdkVersion to 21 in the AndroidManifest.xml file allows me to build fine.

Is this plugin compatible with Support Library v4? (As in this answer - http://stackoverflow.com/a/36788905/846727 ?)

**Comment by NiklasMerz** [comment]
Have you tried building my [demo project](https://github.com/NiklasMerz/fingerprint-aio-demo)? 
It is set to target version 23 and min sdk 16. This should work.

I never tried using Support Library. If you are trying this, I would appreciate feedback if this works. I will have a look myself soon.

**Comment by kunal999** [comment]
Thanks for your response. I tried building, but unfortunately I get the following error:-

```[11:15:21]  typescript: C:/w/git/fingerprint-aio-demo/src/pages/home/home.ts, line: 2
            Module '"C:/w/git/fingerprint-aio-demo/node_modules/ionic-native/dist/es5/index"' has no exported member
            'FingerprintAIO'.

       L1:  import { Component } from '@angular/core';
       L2:  import { FingerprintAIO } from 'ionic-native'

[11:15:21]  transpile failed```

Seems to me like a different issue however.

**Comment by NiklasMerz** [comment]
Are you using Typescript? This looks like an issue from ionic 2 / ionic native.

**Comment by kunal999** [comment]
Yeah the issue with your demo looks like it is `ionic-native` related. It seems that may have removed your plugin from there. However, I don't know why the code in the `master` branch is looking for `ionic-native`.

On my project, I am not using Typescript. Actually it is ionic 1 and Ionic CLI version is 1.7.16.

**Comment by NiklasMerz** [comment]
@kunal999 Thanks for reporting this. I somehow managed to mess up master. Master should now be able to build. It is now a blank ionic project with calls to this plugin in plain javascript. Please close this issue if it is build for you. Looking forward hearing your feedback,

**Comment by kunal999** [comment]
I am getting the same build error as my own project.
```FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Error: cmd: Command failed with exit code 1 Error output:
invalid resource directory name: C:\w\git\fingerprint-aio-demo\platforms\android\build\intermediates\res\merged\debug/drawable-anydpi-v21
```

Are you able to build successfully? What is your version of the `cordova-android` library? `cordova` CLI?
Here is my platform
```Your system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.2
Xcode version: Not installed
```

`cordova-android` version is `6.1.2`. Also JDK is `1.8.0_121`.
`Android SDK Tools` is `25.2.5` and `Android SDK Platform-tools` is `25.0.4`.

Thanks!

**Comment by NiklasMerz** [comment]
My demo project build with min SDK 16 on my machine [Master](https://github.com/NiklasMerz/fingerprint-aio-demo/blob/master/config.xml). Probably this is a problem with your build environment. Did you try removing and adding platform android again? I dont think build with min SDK 16 should be a problem with this plugin.

**Comment by kunal999** [comment]
It is quite possible it could be an issue with my environment. I have removed and added the android platform multiple times. With no success. The only think that allows me to build is if I change the minSdkVersion to 21.
Do you mind sharing your environment? `ionic info`?
Specifically I am interested in the version of `cordova-android`. It should be in `platforms.json`.

Thanks!

**Comment by NiklasMerz** [comment]
Maybe you should try setting up a new environment. My main desktop doesnt build this project, too. My laptop works:

```
Your system information:

Cordova CLI: 7.0.0 
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v4.5.0
Xcode version: Not installed
```

I recently updated cordova and ionic cli.

**Comment by NiklasMerz** [comment]
I am closing this for now. Let me know if you have still issues getting this plugin to work.
