### ISSUE TITLE
touchIDNotAvailable is depreated since iOS 11

### ISSUE THREAD

**Issue by NiklasMerz** [NiklasMerz/cordova-plugin-fingerprint-aio#170]
### Bug report
... use LABiometrytypeNotAvailable instead.

**Comment by NiklasMerz** [comment]
@bennokress Do you know how to replace this properly? Thanks

**Comment by bennokress** [comment]
This is already fixed with #139 and can be closed 😉

**Comment by NiklasMerz** [comment]
Nice, couldn't remember that. Thanks
