### ISSUE TITLE
iOS: no way to check if fingerprint authentication with passcode fallback is available

### ISSUE THREAD

**Issue by dmitry-salnikov** [NiklasMerz/cordova-plugin-fingerprint-aio#175]
In iOS implementation, logic for checking authentication capabilities differs. 

In `isAvailable` plugin API method, the policy being checked with `canEvaluatePolicy` is `.deviceOwnerAuthenticationWithBiometrics`, which means biometric auth only with no fallback to passcode check. But, the `authenticate` plugin method takes as parameter `disableBackup`, which determines which policy to evaluate - with or without fallback, and default value is `.deviceOwnerAuthentication` which means to use password auth fallback and differs from behavior of `isAvailable` API. 

To make this behavior equal, `isAvailable` should also take some parameter to specify which policy to check.

**Comment by daemons88** [comment]
I fix that using this:

```swift
@objc(Fingerprint) class Fingerprint : CDVPlugin {
    
    fileprivate var policy:LAPolicy!
    
    func isAvailable(_ command: CDVInvokedUrlCommand){
```
remove the other policy in the code and add this:

```swift
override func pluginInitialize() {
        super.pluginInitialize()
        
        policy = .deviceOwnerAuthenticationWithBiometrics
    }
```

**Comment by NiklasMerz** [comment]
The `isAvailable` check was intended to check for biometrics. But I get your point and you could create a PR with an optional new parameter to check for backup.

**Comment by dmitry-salnikov** [comment]
@NiklasMerz later is better than never :) so I've prepared the PR finally https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/pull/258  please take a look
