### ISSUE TITLE
face id integration in ios

### ISSUE THREAD

**Issue by jagatb880** [NiklasMerz/cordova-plugin-fingerprint-aio#183]
#### Feature Description
How to use face id for ios and where to get the
localizedFallbackTitle: 'Use Pin', //Only for iOS
    localizedReason: 'Please authenticate' //Only for iOS

and is there any special permission or any thing need for this

**Comment by NiklasMerz** [comment]
If faceID is avaible it is used automatically.

I am closing this now, because this is a question and not an issue. If you have any questions feel free to use Gitter](https://gitter.im/cordova-plugin-fingerprint-aio).
