### ISSUE TITLE
Compile With PhonegapBuild “Use Legacy Swift Language Version”

### ISSUE THREAD

**Issue by alvarheras** [NiklasMerz/cordova-plugin-fingerprint-aio#19]
## Description

When i compile in PHONEGAP BUILD The error in log phonegap build i that -->

### Logs

“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

Thax

**Comment by alvarheras** [comment]
I think that you solve the problem eliminate lines ; of code that like this : 
`import Foundation
import LocalAuthentication

@objc(Fingerprint) class Fingerprint : CDVPlugin {

  func isAvailable(_ command: CDVInvokedUrlCommand) {
    let authenticationContext = LAContext()
    var error:NSError?

    let available = authenticationContext.canEvaluatePolicy(.deviceOwnerAuthenticationWithBiometrics, error: &error)

    var pluginResult = CDVPluginResult(status: CDVCommandStatus_ERROR, messageAs: "Not available")
    if available == true {
      pluginResult = CDVPluginResult(status: CDVCommandStatus_OK, messageAs: "Available")
    }

    commandDelegate.send(pluginResult, callbackId:command.callbackId)
  }
  func authenticate(_ command: CDVInvokedUrlCommand) {

      let authenticationContext = LAContext()
      var pluginResult = CDVPluginResult(status: CDVCommandStatus_ERROR, messageAs: "Something went wrong")
      var reason = "Authentication";
      let data  = command.arguments[0] as AnyObject?

      if let clientId = data?["clientId"] as! String? {
        reason = clientId
      }
      authenticationContext.evaluatePolicy(
        .deviceOwnerAuthenticationWithBiometrics,
        localizedReason: reason,
        reply: { [unowned self] (success, error) -> Void in
          if( success ) {
            pluginResult = CDVPluginResult(status: CDVCommandStatus_OK, messageAs: "Success")
          }else {
            // Check if there is an error
            if error != nil {
              pluginResult = CDVPluginResult(status: CDVCommandStatus_ERROR, messageAs: "Error: \(error)")
            }
          }
          self.commandDelegate.send(pluginResult, callbackId:command.callbackId)
        });
        
    } 
  }
`

**Comment by alvarheras** [comment]
I find error :
 func authenticate(command: CDVInvokedUrlCommand) { ... without _ syntax

**Comment by alvarheras** [comment]
please commit the change

**Comment by NiklasMerz** [comment]
I never used Phonegap Build. XCode does not convert the Swift syntx. What do you think is the problem?

**Comment by alvarheras** [comment]
For compile in phonegap build should update the syntax swift to 3.1 like QRScanner inssue -->https://github.com/bitpay/cordova-plugin-qrscanner/commits/master/src/ios/QRScanner.swift

This solved problem for compile with phonegap build

**Comment by NiklasMerz** [comment]
XCode indeed marks errors in the file, but if i change the syntaxt the compiled app does not work for me. If I don´t resolve the issues the app builds aswell and runs perfectly. I am not a Swift expert but I will look at this.

**Comment by alvarheras** [comment]
Hi Niklas , i dont stand how you compile with XCODE because the syntax send me a error. I think that the version of xcode can be affected to compile . How you compile the app with this errors? 
![captura de pantalla 2017-05-22 a las 9 27 37](https://cloud.githubusercontent.com/assets/11508953/26296964/3911e48c-3ed1-11e7-88f1-40e2bb9f5144.png)
Thax :)

**Comment by NiklasMerz** [comment]
Hi

Can you confirm that this plugin works with your Xcode and phonegap build when you changed the syntax? Which Xcode version do you use? My Xcode also shows theese errors but after compile the disappear and the plugin works with the demo project.

**Comment by alvarheras** [comment]
Hello, I use Xcode 8.0 . I can compile in Xcode when push like this legacy swift:

![captura de pantalla 2017-05-23 a las 14 31 30](https://cloud.githubusercontent.com/assets/11508953/26354370/9b04b7c0-3fc4-11e7-8efa-25a5580dd7fb.png)

In phonegap build i can put in config.xml file this:

`<preference name="UseLegacySwiftLanguageVersion" value="true" />`

And indicate the version Swift 3.0 in config too but not working , this is not inssue for your plugin , is for phonegapbuild . It´s ok thax , you can close the inssue

**Comment by NiklasMerz** [comment]
Ok. If you have tips for using this this plugin with phonegap build, you could create a pull request for with a description in README or changes.
