### ISSUE TITLE
Fingerprint message doesn't always appear

### ISSUE THREAD

**Issue by neluskoevoet** [NiklasMerz/cordova-plugin-fingerprint-aio#191]
Hi, I am using the fingerprint-aio plugin within an ionic project, but i am encountering an issue with the popup that shows that you can use you're fingerprint to unlock the app. sometimes the popup wil show directly when the app initialize and sometimes it takes a while, or it doesn't show at all. When i touch the homebutton of my Iphone it wil trigger the fingerprint signin and show the popup message.

My question, how can it be that the message does not always show at the same time (when initializing the app/and when resuming the app)

**Comment by nwocykra** [comment]
Im also experiencing this exact issue and curious for a solution.

For some reason it appears worse today than yesterday. Today im only getting the faulty behaviour with the same code.

Could be a problem on the part of Apple?

**Comment by jayrchamp** [comment]
@neluskoevoet @nwocykra 
This bug seems to be on Apple' side. I have experienced the same behavior while trying to access Settings -> Password & account. I clicked on "Passwords (Web/apps)" and then nothing happens, if I press the Home button the touch id popup suddendly appears.

**Comment by neluskoevoet** [comment]
The problem has been solved with the new IOS update 13.1.3
