### ISSUE TITLE
Choose authentication type depending on availability

### ISSUE THREAD

**Issue by sygmakikus** [NiklasMerz/cordova-plugin-fingerprint-aio#195]
#### Feature Description
We have been using this plugin for a while and it usually works really well. However we ran into a problem which we are not able to solve programatically, I hope I can explain it correctly.

We have multiple test devices, including:

- iPhone X: which has "face" authentication type
- iPhone 6: which has "finger" authentication type
- Huawei: which has "finger" authentication type
- OnePlus: which has both "finger" and "face" authentication type - **the problem is here**

After some tests, even though we have the Android OnePlus device with both authentication methods available (I can unlock the phone with both my face and my finger) the plugin always returns "finger" as authentication type. Is there a way to use "face" authentication instead?

Right now we are using version 1.7.0 of the plugin but we also tried with version 2.0.0 obtaining the same results.

Thank you in advance

**Comment by NiklasMerz** [comment]
This plugin supports only finger authentication on Android currently. There is work in progress for the new biometric API on Android in #179 . Feel free to test this and report back, if you need help or find bugs.

**Comment by NiklasMerz** [comment]
We now support biometric prompt. Additional testing required.

**Comment by mithila1993** [comment]
Hi @NiklasMerz, 
Thanks for your amazing plugin. 
I tested the latest plugin yesterday and these are results

**Samsung | Android version 10 | Working | Working | Can toggle with face and touch.  Both works perfectly
Samsung | Android version 9 | Working | Working | Can't toggle with face and touch. Sometimes it appears Face ID and sometimes it appears Touch ID. it looks like a plugin bug.
Huawei | Android version 10 | Not working 
Huawei | Android version 9 | Not working** 

As a summary, The plugin is not working on Huawei phones and not properly working on Samsung Android 9 version

Please give your kind attention for this

**Comment by NiklasMerz** [comment]
As I don't have access to these phone I cannot do anything about that. If you find issues and fix them in a pull request I am happy to review it.

This plugin implements a standard Android API. Some manifacturers/devices implement it strangely and I cannot do anything about that.

I working on this in my free time and I own just one Android device (OnePlus 6T). OnePlus did not do this API great for my device, too. As I don't get paid for working on this plugin I cannot work much on this and depend on community contributions.

**Comment by mithila1993** [comment]
Yes @NiklasMerz .. It is true.. Thanks for your quick reply and amazing plugin again.

**Comment by NiklasMerz** [comment]
I moved discussions around biometric types here: https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/discussions/303

Better support for Android has to come from the community. I don't have the resources and motivation to work on this, sorry. 

But this is now off-topic ;-)
