### ISSUE TITLE
Ambiguous use of 'subscript(_:)' on capacitor

### ISSUE THREAD

**Issue by robertolocal** [NiklasMerz/cordova-plugin-fingerprint-aio#201]
### Bug report
Failed to build on capacitor, showing error Ambiguous use of 'subscript(_:)' on Fingerprint.swift at lines 57, 62, 69 and 71.

## Description

* What did you do? Install plugin and try to build on ios
* What did happen? Fail
* What did you expect to happen? Succed

## Environment

* Plugin version: latest
* Build environment (```cordova info```)
Installed platforms:
  android 8.1.0
  ios 4.5.5

### Logs

<details>
  <pre>Ambiguous use of 'subscript(_:)</pre>
</details>

**Comment by NiklasMerz** [comment]
Duplicate with more comments in #295
