### ISSUE TITLE
Update for examples due to removed clientId and clientSecret

### ISSUE THREAD

**Issue by rubenCodeforges** [NiklasMerz/cordova-plugin-fingerprint-aio#206]
### Feature Request
Examples and video should be update since v3
#### Feature Description
In `v3` there is no `clientId` or `clientSecret` , but the examples and the video shows it.
Also there should be perhaps a note in the release notes , since updating to `v3` in from older version will cause a build error as `clientId` and clientSecret are no more.
Maybe a small update guide should be posted somewhere ?

**Comment by NiklasMerz** [comment]
Thank you for your suggestions.

We should remove the examples. They are very old and somewhat deprecated.

The video is nice, but old, too. I think we should add a hint to that.

**Comment by rubenCodeforges** [comment]
@NiklasMerz the point is , that v3 does not opens the dialog on a android v8

**Comment by NiklasMerz** [comment]
It should work on Android 8! What is the problem? Could you provide logs or code?

**Comment by marcinphero** [comment]
On Android 8 with v3 plugin it works very strange. Instead of biometrics popup (which was on plugin v1) it shows me strange system screen code input. After providing such it goes back to the app but nothing happens.

**Comment by rubenCodeforges** [comment]
@marcinphero can you share a screen please ?

**Comment by marcinphero** [comment]
![IMG_0001](https://user-images.githubusercontent.com/44893979/69426886-948ac300-0d2e-11ea-9895-1610bfaca8c8.JPG)

**Comment by greaterking** [comment]
What device is this? This should work based on all the testing before release

**Comment by marcinphero** [comment]
Honor 9, official android 8
