### ISSUE TITLE
Build Error under ionic 3

### ISSUE THREAD

**Issue by hydrococcous** [NiklasMerz/cordova-plugin-fingerprint-aio#207]
### Bug report
If I try to build my ionic3 App with the Plugin Version 3.0.0 i get the following Build Error:

> \platforms\android\app\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:89: error: cannot find symbol
                .getSystemService(this, KeyguardManager.class);

## Description

* What did you do?
* What did happen?
* What did you expect to happen?

## Environment

* Plugin version 3.3.0
* Build environment (```cordova info```)

<pre>
Ionic:

   Ionic CLI          : 5.4.2
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.3

Cordova:

   Cordova CLI       : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : no whitelisted plugins (35 plugins total)

Utility:

   cordova-res : 0.7.0
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 (C:\Users\username\AppData\Local\Android\sdk)
   NodeJS            : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10
</pre>

* ```cordova platform ls```

<pre>
Installed platforms:
  android 8.1.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~6.0.0

</pre>
### Logs

  <pre>
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

</pre>

**Comment by NiklasMerz** [comment]
Did you deleting the Android Platform and adding it again?

**Comment by hydrococcous** [comment]
Yes, I delete the platform complete, also the plugin. After that i reinstall the Plugin with:
<pre>
ionic cordova plugin add cordova-plugin-fingerprint-aio
npm install --save @ionic-native/fingerprint-aio@4
</pre>

And readd the Platform with:
<pre>
ionic cordova platform add android@8.1.0
</pre>

If i try it in an new ionic 3 Project, the Build Process works. Dont know why.

**Comment by NiklasMerz** [comment]
Do you have any other plugins that may conflict?

**Comment by hydrococcous** [comment]
All other Plugins working. Here is the list:
<pre>
com-darryncampbell-cordova-plugin-intent 1.1.8 "Intent Shim"
cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-advanced-http 2.1.1 "Advanced HTTP plugin"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-contacts 3.0.1 "Contacts"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-opener2 2.1.4 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filechooser 1.2.0 "File Chooser"
cordova-plugin-filepath 1.0.2 "FilePath"
cordova-plugin-filepicker 1.1.6 "File Picker"
cordova-plugin-fingerprint-aio 1.7.0 "FingerprintAllInOne"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ios-keychain 3.0.1 "KeyChain Plugin for Cordova iOS"
cordova-plugin-mfilechooser 1.0.5 "Evolution36 filechooser"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-secure-storage 2.6.8 "SecureStorage"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-telerik-imagepicker 2.3.3 "ImagePicker"
cordova-plugin-themeablebrowser 0.2.17 "ThemeableBrowser"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.4.6 "SocialSharing"
cordova-sqlite-storage 3.3.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-deeplinks 1.0.20 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 8.0.1 "BarcodeScanner"

</pre>

**Comment by hydrococcous** [comment]
Ok, I think I have locatred the Problem:

`cordova-android-support-gradle-release`

I have uninstall the Plugin and Build  Successfull

**Comment by NiklasMerz** [comment]
Great never heard about that plugin,
