### ISSUE TITLE
Capacitor: Failed to transform file 'android-biometric.aar'

### ISSUE THREAD

**Issue by CherifKods** [NiklasMerz/cordova-plugin-fingerprint-aio#209]
Hello,

I'm trying to integrate the fingerprint AIO in my ionic application that works with capacitor ,
 this is the way I installed the plugin

1. create the ionic app 
=> I test it ,it works fine
2. I installed the plugin with
npm install  git+https://github.com/NiklasMerz/capacitor-fingerprint-app.git
npm install @ionic-native/fingerprint-aio
 npx cap sync
 ionic capacitor run android
I build from android studio ..
 => I test it,an error with plugin not installed...

I try with 
npm install cordova-plugin-fingerprint-aio
npx cap sync 
ionic capacitor run android 
sync the project with gradle files ,build fails with 
 **Errors** 
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Failed to transform file 'android-biometric.aar' to match attributes {artifactType=processed-aar} using transform IdentityTransform

ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Failed to transform file 'android-biometric.aar' to match attributes {artifactType=processed-aar} using transform IdentityTransform

ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Failed to transform file 'android-biometric.aar' to match attributes {artifactType=processed-aar} using transform IdentityTransform

Am I doing something wrong in here or there is a problem with the plugin?

PS: I tried to build the plugin project without integrating it in my app  and it works fine 

Can you please help me with this,

Thank you,

**Comment by OlegIvaniv** [comment]
Hi, did somebody manage to make the version 3.0 work on Android? @exxbrain, can you please chip-in? Would appreciate any help or a nudge in the right direction 🙂

Cheers!

**Comment by SergioSuarezDev** [comment]
some here with v3.0

**Comment by exxbrain** [comment]
Hi, what is Capacitor?

**Comment by NiklasMerz** [comment]
Capacitor is a Cordova alternative created by the ionic Team. It is compatible with Cordova plugins.

I think it would be great if this plugin Was compatible with Capacitor, but I did not test the latest version myself.

**Comment by Proper-Job** [comment]
I created a pull request that fixes this issue for me: https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/pull/217
It turns out that using capacitor the .aar file can't be resolved. Replacing it with a maven reference however seems to solve this issue.
I'm very new to this stack. Could someone test this again?
