### ISSUE TITLE
Add support for setConfirmationRequired for Android

### ISSUE THREAD

**Issue by emfmesquita** [NiklasMerz/cordova-plugin-fingerprint-aio#211]
Just a simple request to expose BiometricPrompt.PromptInfo builder option setConfirmationRequired for Android.

The reason I ask is that for Pixel 4 every time the prompt comes up there is a confirmation button:

![image](https://user-images.githubusercontent.com/8060611/70250112-66a07800-174b-11ea-8b0c-3298f5546daf.png)

Thanks

**Comment by NiklasMerz** [comment]
I don't own a Pixel. How does the confirm work.

@exxbrain and @greaterking please correct me if I am wrong.

I guess this confirm is part of the Biometric prompt as implemented by Google for Pixel devices and we have no access to this?

**Comment by mibrito707** [comment]
Hello guys, I just opened a PR to add this feature #222 
@NiklasMerz [here](https://developer.android.com/training/sign-in/biometric-auth#no-explicit-user-action), [here](https://developer.android.com/reference/androidx/biometric/BiometricPrompt.PromptInfo.Builder.html#setConfirmationRequired(boolean)) and [here](https://android-developers.googleblog.com/2019/10/one-biometric-api-over-all-android.html) you can find great documentation on how `setConfirmationRequired()` works.
