### ISSUE TITLE
NSInvalidArgumentException on ios

### ISSUE THREAD

**Issue by vcomperq** [NiklasMerz/cordova-plugin-fingerprint-aio#212]
Hi,

i'm testing your plugin in my ios device.
Here is the error that i get : 

> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Non-empty localizedReason must be provided.

this error happens when i call the "show" method

My app is written with the ionic 4 framework and the plugin version is 3.0.0

Thanks

**Comment by vcomperq** [comment]
please see : https://github.com/ionic-team/ionic-native/issues/3239

**Comment by NiklasMerz** [comment]
Please see the documentation of this plugin and ionic-team/ionic-native#3227 for the latest changes.

**Comment by vcomperq** [comment]
the ionic documentation says : 

> import { FingerprintAIO } from '@ionic-native/fingerprint-aio/ngx';

constructor(private faio: FingerprintAIO) { }

...

this.faio.show({
    clientId: 'Fingerprint-Demo', //Android: Used for encryption. iOS: used for dialogue if no `localizedReason` is given.
    clientSecret: 'o7aoOMYUbyxaD23oFAnJ' //Necessary for Android encrpytion of keys. Use random secret key.
    disableBackup:true,  //Only for Android(optional)
    localizedFallbackTitle: 'Use Pin', //Only for iOS
    localizedReason: 'Please authenticate' //Only for iOS
})
.then((result: any) => console.log(result))
.catch((error: any) => console.log(error));


why do i have an error about the localizedReason while this params does nos exist anymore

**Comment by greaterking** [comment]
Looks like you updated the plug-in without updating to the latest ionic wrapper? In your project try running:

`npm install @ionic-native/fingerprint-aio`

**Comment by vcomperq** [comment]
i updated nothing, i just did  : 

ionic cordova plugin add cordova-plugin-fingerprint-aio
npm install @ionic-native/fingerprint-aio

for the following results in my package.json : 

"@ionic-native/fingerprint-aio": "^5.17.1",
"cordova-plugin-fingerprint-aio": "^3.0.0",

and this issue has been closed  3 hours ago but the problem is still there...

**Comment by greaterking** [comment]
Thats so weird..from your project when you navigate to /node_modules/@ionic-native/fingerprint-aio/ngx/index.d.ts do you see a property called "fallbackButtonTitle" in that file?

**Comment by vcomperq** [comment]
yes i do

**Comment by NiklasMerz** [comment]
Did you provide that paramter for show? Please try deleting the ios platform and create it again

**Comment by vcomperq** [comment]
i add this params and it's working now.

Very strange because, i removed it, and it's still ok
i tried with an other blank app, without any params, it's also working...

so it's ok, yes, but i don't understand why...

Anyway, thanks for your help !

**Comment by NiklasMerz** [comment]
That' strange. But as it not reproducible I don't think we have a bug here.

**Comment by vyelamanchi** [comment]
Hi,

Recently upgraded the ionic version to 5.0.0 & all the native plugins.

"@ionic-native/fingerprint-aio": "^5.21.5"
"cordova-plugin-fingerprint-aio": "3.0.1",

Receiving the same "Non-empty localizedReason must be provided" error when trying to "show" the auth dialog on IOS .

**Comment by vyelamanchi** [comment]
"localizedReason: 'Please authenticate' //Only for iOS" 
This option only exists for the old version for the plugin.

**Comment by vyelamanchi** [comment]
Swift version 5

**Comment by vyelamanchi** [comment]
Found & fixed the issue. I was setting the “description” attribute in fingerprintoptions to empty quotes.

**Comment by NiklasMerz** [comment]
Great thanks for reporting
