### ISSUE TITLE
Use PIN fallback when fingerprint is not available any more

### ISSUE THREAD

**Issue by Filavision** [NiklasMerz/cordova-plugin-fingerprint-aio#214]
### Feature Request
Use the PIN when fingerprint is not available any more
#### Feature Description
I have users where the fingerprint sensor is broken and they can't login any more. Is it possible to use just the PIN in this case? Like:
Fingerprint.isAvailable(NormalFingerprintCheck, UsePINFallback);

**Comment by NiklasMerz** [comment]
Check out the features of the biometric API https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/discussions/303
