### ISSUE TITLE
Clashing with Telerik-Verified-Plugins/ImagePicker

### ISSUE THREAD

**Issue by parthnayak7448** [NiklasMerz/cordova-plugin-fingerprint-aio#216]
I am using ionic 4 and Capacitor framework. 
I am using [https://github.com/Telerik-Verified-Plugins/ImagePicker] plugin for multiple image picker from gallery. 
When i use cordova-plugin-fingerprint-aio in the project it clash with the imagepicker plugin and builds fail in ios with error 'UIImage+fixOrientation.m' file not found error

**Comment by NiklasMerz** [comment]
I cannot image how this plugin could cause this error. Please post more logs and your findings.
