### ISSUE TITLE
Identify biometric type from isAvailable() function

### ISSUE THREAD

**Issue by juicyapphk** [NiklasMerz/cordova-plugin-fingerprint-aio#223]
#### Feature Description
From current plugin version (v3.0.0) on Android, the isAvailable() function will only return either "biometric" (for Anroid P+) or "finger" (for older version) value.

Instead of "biometric" , is there any way we can identify whether the available biometric method is "Face Recognization" or "Fingerprint"?

Alternatively, will you consider separating the functions like:
- From isAvailable() to: isFaceAuthAvailable() and isFingerprintAuthAvailable()
- From show() to: showFaceAuth() and showFingerprintAuth()

Thanks for your great work!

**Comment by NiklasMerz** [comment]
I think there is now way in the Biometric Prompt API to determine which type is available.

See https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/pull/179#issuecomment-543473850
And https://issuetracker.google.com/issues/111315641

@exxbrain Correct me if I'm wrong.

**Comment by derek90** [comment]
I'm not sure, but I'm assuming that if the platform is Android, 'biometric' will mean fingerprint (is there an android device with face recognition? I guess just iPhone has it)

**Comment by takhil** [comment]
Hi Nik,

I'm facing same issue with android 9 operating system(samsung s 9 model) which has both face id and touch id and device is prompting for face id but, when I use plugin  version 1.7.0 works fine with touch id as authentication mode with plugin version 3.0.1 it is looking for face id. 

Is there any thing need to be updated from my side to handle this or device functionality ?

**Comment by NiklasMerz** [comment]
Please check out https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/discussions/303
