### ISSUE TITLE
can i register and login by using this plugin??

### ISSUE THREAD

**Issue by kiruba-sankar** [NiklasMerz/cordova-plugin-fingerprint-aio#225]
I need to create an app in ionic 4 with register and login by finger print. can anyone help me pls??

**Comment by NiklasMerz** [comment]
Github issues are intended for bug reports and features. You request is more a question. You should find tutorials on the internet. This one is older but you might learn something from it: https://www.youtube.com/watch?v=tQDChMJ6er8

You should implement your apps login and register with your backend or some third-party authorization provider. This plugin is more for fingerprint lock of the app. So it shows a prompt after starting the app for example.
