### ISSUE TITLE
IOS: Non-empty localizedReason must be provided

### ISSUE THREAD

**Issue by vyelamanchi** [NiklasMerz/cordova-plugin-fingerprint-aio#228]
Hi,

Recently upgraded the ionic version to 5.0.0 & all the native plugins.

"@ionic-native/fingerprint-aio": "^5.21.5"
"cordova-plugin-fingerprint-aio": "3.0.1",

Tried Swift version 4 & 5.

Receiving error "Non-empty localizedReason must be provided" when trying to "show" the biometric authentication dialog on IOS .

**Comment by vyelamanchi** [comment]
OK. found the issue.
I wasn't setting the "description" attribute. Looks like that is required for IOS.
I was passing empty quotes.

**Comment by Aguirrehub25** [comment]
El info.plist se configura alguna clave ?
