### ISSUE TITLE
BiometricActivity.java:89 error getSystemService

### ISSUE THREAD

**Issue by johnjackson** [NiklasMerz/cordova-plugin-fingerprint-aio#229]
### Bug report
<img width="1279" alt="WechatIMG206" src="https://user-images.githubusercontent.com/2791968/75005439-693c7f00-54a9-11ea-9854-95349b79aa6d.png">

/Users/johnjackson/workspace/ionicpro_slide_blue_ionic4/platforms/android/app/src/main/java/de/niklasmerz/cordova/biometric/BiometricActivity.java:89:  error: 找不到符号
                .getSystemService(this, KeyguardManager.class);
                ^

## Description

I got this error when I use ionic4 ionic-native plugin Fingerprint AIO (https://ionicframework.com/docs/native/fingerprint-aio), 

ionic cordova run android 

## Environment
* Plugin version
    "@ionic-native/fingerprint-aio": "^5.21.5",
    "cordova-plugin-fingerprint-aio": "^3.0.1",

    "@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@ionic/angular": "^4.11.2",

* Build environment (```
jmbp% cordova info
cordova-lib@9.0.1 with:
  cordova-common@3.2.0
  cordova-create@2.0.0
  cordova-fetch@2.0.1
  cordova-serve@3.0.0

Environment:
  OS: darwin
  Node: v11.4.0
  npm: 6.13.7

Plugins:
  code-push
  cordova-android-support-gradle-release
  cordova-plugin-aes256-encryption
  cordova-plugin-android-permissions
  cordova-plugin-app-version
  cordova-plugin-calendar
  cordova-plugin-camera
  cordova-plugin-code-push
  cordova-plugin-datepicker
  cordova-plugin-device
  cordova-plugin-dialogs
  cordova-plugin-file
  cordova-plugin-file-opener2
  cordova-plugin-file-transfer
  cordova-plugin-filechooser
  cordova-plugin-filepath
  cordova-plugin-fingerprint-aio
  cordova-plugin-inappbrowser
  cordova-plugin-ionic-keyboard
  cordova-plugin-ionic-webview
  cordova-plugin-jcore
  cordova-plugin-network-information
  cordova-plugin-privacyscreen
  cordova-plugin-screen-orientation
  cordova-plugin-splashscreen
  cordova-plugin-statusbar
  cordova-plugin-whitelist
  cordova-plugin-zip
  cordova-sqlite-storage
  es6-promise-plugin
  jpush-phonegap-plugin

Android platform:
  Available Android targets:
  ----------
  id: 1 or "android-26"
       Name: Android 8.0.0
       Type: Platform
       API level: 26
       Revision: 2
       Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
   Tag/ABIs : no ABIs.
  ----------
  id: 2 or "android-27"
       Name: Android 8.1.0
       Type: Platform
       API level: 27
       Revision: 3
       Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
   Tag/ABIs : no ABIs.
  ----------
  id: 3 or "android-28"
       Name: Android 9
       Type: Platform
       API level: 28
       Revision: 6
       Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
   Tag/ABIs : no ABIs.

config.xml <<EOF
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.hse.scarffold.ionic4" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>移动脚手架v4</name>
    <description>An awesome Ionic/Cordova app.</description>
    <author email="hi@ionicframework.com" href="http://ionicframework.com/">Ionic Framework Team</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="ScrollEnabled" value="false" />
    <preference name="android-minSdkVersion" value="19" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <platform name="android">
        <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
            <application android:networkSecurityConfig="@xml/network_security_config" />
        </edit-config>
        <resource-file src="resources/android/xml/network_security_config.xml" target="app/src/main/res/xml/network_security_config.xml" />
        <allow-intent href="market:*" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
        <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
        <icon height="20" src="resources/ios/icon/icon-20.png" width="20" />
        <icon height="40" src="resources/ios/icon/icon-20@2x.png" width="40" />
        <icon height="60" src="resources/ios/icon/icon-20@3x.png" width="60" />
        <icon height="48" src="resources/ios/icon/icon-24@2x.png" width="48" />
        <icon height="55" src="resources/ios/icon/icon-27.5@2x.png" width="55" />
        <icon height="29" src="resources/ios/icon/icon-29.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-29@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-29@3x.png" width="87" />
        <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        <icon height="120" src="resources/ios/icon/icon-40@3x.png" width="120" />
        <icon height="88" src="resources/ios/icon/icon-44@2x.png" width="88" />
        <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
        <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
        <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
        <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
        <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
        <icon height="167" src="resources/ios/icon/icon-83.5@2x.png" width="167" />
        <icon height="172" src="resources/ios/icon/icon-86@2x.png" width="172" />
        <icon height="196" src="resources/ios/icon/icon-98@2x.png" width="196" />
        <icon height="1024" src="resources/ios/icon/icon-1024.png" width="1024" />
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
        <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
        <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
        <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
        <splash height="1125" src="resources/ios/splash/Default-Landscape-2436h.png" width="2436" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
        <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="2732" src="resources/ios/splash/Default-Portrait@~ipadpro.png" width="2048" />
        <splash height="2048" src="resources/ios/splash/Default-Landscape@~ipadpro.png" width="2732" />
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
        <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
        <splash height="2436" src="resources/ios/splash/Default-2436h.png" width="1125" />
        <splash height="2732" src="resources/ios/splash/Default@2x~universal~anyany.png" width="2732" />
    </platform>
    <plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-statusbar" spec="2.4.2" />
    <plugin name="cordova-plugin-device" spec="2.0.2" />
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="^4.0.0" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" />
    <plugin name="cordova-sqlite-storage" spec="^3.4.0" />
</widget>

EOF

package.json <<EOF
{
  "name": "ionic4_test_plugin",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/http": "^5.2.11",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@ionic-enterprise/cordova": "^9.0.3",
    "@ionic-native/aes-256": "^5.21.0",
    "@ionic-native/android-permissions": "^5.16.0",
    "@ionic-native/app-version": "^5.16.0",
    "@ionic-native/calendar": "^5.16.0",
    "@ionic-native/camera": "^5.15.1",
    "@ionic-native/code-push": "^5.15.1",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/file": "^5.15.1",
    "@ionic-native/file-chooser": "^5.15.1",
    "@ionic-native/file-encryption": "^5.21.0",
    "@ionic-native/file-opener": "^5.16.0",
    "@ionic-native/file-path": "^5.16.0",
    "@ionic-native/file-transfer": "^5.15.1",
    "@ionic-native/fingerprint-aio": "^5.21.5",
    "@ionic-native/in-app-browser": "^5.16.0",
    "@ionic-native/media": "^5.15.1",
    "@ionic-native/media-capture": "^5.15.1",
    "@ionic-native/network": "^5.16.0",
    "@ionic-native/safari-view-controller": "^5.16.0",
    "@ionic-native/screen-orientation": "^5.16.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/sqlite": "^5.16.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.11.2",
    "@ionic/storage": "^2.2.0",
    "@jiguang-ionic/jpush": "^2.0.0",
    "@types/echarts": "^4.4.0",
    "angular-tree-component": "^8.5.1",
    "angular2-signaturepad": "^2.9.0",
    "code-push": "^3.0.1",
    "cordova-android": "^8.1.0",
    "cordova-android-support-gradle-release": "^3.0.1",
    "cordova-plugin-aes256-encryption": "^2.0.0",
    "cordova-plugin-android-permissions": "^1.0.2",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-calendar": "^5.1.5",
    "cordova-plugin-camera": "^4.1.0",
    "cordova-plugin-code-push": "^1.12.0",
    "cordova-plugin-datepicker": "^0.9.3",
    "cordova-plugin-dialogs": "^2.0.2",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-opener2": "^2.2.1",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-filechooser": "^1.2.0",
    "cordova-plugin-filepath": "^1.5.6",
    "cordova-plugin-fingerprint-aio": "^3.0.1",
    "cordova-plugin-inappbrowser": "^3.1.0",
    "cordova-plugin-jcore": "^1.3.1",
    "cordova-plugin-network-information": "^2.0.2",
    "cordova-plugin-screen-orientation": "^3.0.2",
    "cordova-plugin-zip": "^3.1.0",
    "cordova-sqlite-storage": "^3.4.0",
    "core-js": "^2.5.4",
    "echarts": "^4.4.0",
    "es6-promise-plugin": "^4.2.2",
    "hammerjs": "^2.0.8",
    "ionic-gallery-modal": "^0.2.7",
    "ionic4-gallery-modal": "0.0.4",
    "jpush-phonegap-plugin": "^3.7.3",
    "ng2-dragula": "^2.1.1",
    "ng2-pdf-viewer": "^6.0.1",
    "no-double-clicks": "^1.0.1",
    "node-sass": "^4.12.0",
    "rxjs": "^6.5.4",
    "rxjs-compat": "^6.5.3",
    "ts-md5": "^1.2.7",
    "tslib": "^1.9.0",
    "vconsole": "^3.3.4",
    "watermark": "^1.5.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular-devkit/core": "~8.1.2",
    "@angular-devkit/schematics": "~8.1.2",
    "@angular/cli": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@ionic/angular-toolkit": "~2.0.0",
    "@ionic/app-scripts": "^3.2.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.1.1",
    "cordova-plugin-splashscreen": "5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "1.3.3",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-file": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-code-push": {},
      "cordova-plugin-zip": {},
      "cordova-plugin-filechooser": {},
      "cordova-plugin-camera": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-datepicker": {},
      "cordova-plugin-calendar": {},
      "cordova-sqlite-storage": {},
      "cordova-plugin-network-information": {},
      "cordova-plugin-filepath": {},
      "cordova-plugin-jcore": {},
      "jpush-phonegap-plugin": {
        "APP_KEY": "4926b5d7f61946c2817da8aa",
        "CHANNEL": "developer-default"
      },
      "cordova-plugin-screen-orientation": {},
      "cordova-plugin-app-version": {},
      "cordova-plugin-file-opener2": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-inappbrowser": {},
      "cordova-android-support-gradle-release": {
        "ANDROID_SUPPORT_VERSION": "27.+"
      },
      "cordova-plugin-android-permissions": {},
      "cordova-plugin-aes256-encryption": {},
      "cordova-plugin-fingerprint-aio": {}
    },
    "platforms": [
      "android"
    ]
  }
}
EOF
```)
* ```
Installed platforms:
  android 8.1.0
Available platforms:
  browser ^6.0.0
  electron ^1.0.0
  ios ^5.0.0
  osx ^5.0.0
  windows ^7.0.0
```

### Logs

<details>
  <pre>
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugResources

> Task :app:compileDebugJavaWithJavac
/Users/johnjackson/workspace/ionicpro_slide_blue_ionic4/platforms/android/app/src/main/java/de/niklasmerz/cordova/biometric/BiometricActivity.java:88: 错误: 找不到符号
        KeyguardManager keyguardManager = ContextCompat.getSystemService(this, KeyguardManager.class);
                                                       ^
  符号:   方法 getSystemService(BiometricActivity,Class<KeyguardManager>)
  位置: 类 ContextCompat
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
1 个错误

> Task :app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
25 actionable tasks: 5 executed, 20 up-to-date
/Users/johnjackson/workspace/ionicpro_slide_blue_ionic4/platforms/android/gradlew: Command failed with exit code 1 Error output:
/Users/johnjackson/workspace/ionicpro_slide_blue_ionic4/platforms/android/app/src/main/java/de/niklasmerz/cordova/biometric/BiometricActivity.java:88: 错误: 找不到符号
        KeyguardManager keyguardManager = ContextCompat.getSystemService(this, KeyguardManager.class);
                                                       ^
  符号:   方法 getSystemService(BiometricActivity,Class<KeyguardManager>)
  位置: 类 ContextCompat
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
1 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
[ERROR] An error occurred while running subprocess cordova.

        cordova build android --device exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
</pre>
</details>

**Comment by johnjackson** [comment]
the same bug: https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/issues/207

**Comment by iverenshaguy** [comment]
Hi. I have this same issue and uninstalling `cordova-android-support-gradle-release` doesn't fix it.

**Comment by Galiza** [comment]
I'm facing the same issue:

<img width="729" alt="Screenshot 2020-03-05 at 12 53 54" src="https://user-images.githubusercontent.com/9288512/75979250-62b5fa80-5ee0-11ea-93e3-2350d0e07a7a.png">

**Comment by NiklasMerz** [comment]
Please make sure you use Java 8.

**Comment by Galiza** [comment]
@NiklasMerz We use it, though.

<img width="460" alt="Screenshot 2020-03-05 at 13 27 22" src="https://user-images.githubusercontent.com/9288512/75981562-0c978600-5ee5-11ea-85e4-3264e7d34b2f.png">

**Comment by iverenshaguy** [comment]
I fixed my issue by changing all my ANDROID_SUPPORT_VERSIONS to 28, especially the `cordova-android-support-gradle-release` support version. The ContextCompat for 27.+. does not have the `getSystemService` method so I had to make sure the support version for 28 was being used.

**Comment by Galiza** [comment]
@iverenshaguy Tried this, didn't work for me.

**Comment by NiklasMerz** [comment]
Most likely this is just an issue with incorrect developer tools installed.
