### ISSUE TITLE
How to fire Try Face Id Again event on iPhone X

### ISSUE THREAD

**Issue by pmd23** [NiklasMerz/cordova-plugin-fingerprint-aio#235]
Hi Team,

The really good feature developed.

I have 1 question related to face id on iPhone X. when face id is not recognized then **Try Again**  screen will come. When I try to click on the button **Try Face Id Again** which event I will fire again so that face id screen will appear again.

![image](https://user-images.githubusercontent.com/2580866/78325571-9f374d80-7595-11ea-92e9-8dd01eb16107.png)

**Comment by luisbecerraadl** [comment]
I have the same Issue

**Comment by sardapv** [comment]
@pmd23 @luisbecerra  If you guys are using iOS simulator faceID option. After clicking on 'try again face id' it actually starts scanning facce again (on actual phone) on simulator this alert is shown till you actually pass face matched from simulator options. So this is not bug

**Comment by NiklasMerz** [comment]
Yeah this is not a bug. The iOS API works just like that.
