### ISSUE TITLE
AndroidX breaking change for new Ionic Capacitor 2.0

### ISSUE THREAD

**Issue by mburger81** [NiklasMerz/cordova-plugin-fingerprint-aio#237]
### Bug report

We used a lot your plugin also in the new ionic capacitor. They released a new major version in 2.0 which no use AndroidX so your plugin doesn't anymore work on it

This imports seems to be broken
```
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.v4.content.ContextCompat;
import android.support.v7.app.AppCompatActivity;
```
Can you update your plugin to Androidx?

Thx

**Comment by NiklasMerz** [comment]
@exxbrain Do you have an idea?

**Comment by mburger81** [comment]
Changing the imports to
```
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.content.ContextCompat;
```

Seems to work fine on our Android 8 Test device.
Not sure what does it mean for you and backward comp doing so?

**Comment by exxbrain** [comment]
@mburger81 You are right!
@NiklasMerz Probably it makes sense to support both androidx and non-androidx versions

**Comment by damsorian** [comment]
I need this fix, any idea?

**Comment by exxbrain** [comment]
Is it a bug or major feature with breaking changes?

**Comment by NiklasMerz** [comment]
Waiting for Cordova 9 sounds like a good idea. It is not too far away.

**Comment by hamzatrq** [comment]
Facing the same error. When will Cordova 9 release? @mburger81 thank you for the temporary fix.

**Comment by mburger81** [comment]
Does anyone know when we can expect to have android-cordova 9 released. Having a look at the github repo there is no really development on it. Perhaps because it is already read and near to be released?

**Comment by NiklasMerz** [comment]
See #245 

Android 9 is nearing the release. Just be patient.

**Comment by DaanWasscher** [comment]
cordova-android 9 has been released last week, any idea on when the switch to android x can be finalized for this plugin?

**Comment by jimmy-cardenas-adl** [comment]
Use jetifier

```
npm install jetifier
npx jetifier
```

For more info https://capacitorjs.com/docs/android/updating

**Comment by mburger81** [comment]
> Use jetifier
> 
> ```
> npm install jetifier
> npx jetifier
> ```
> 
> For more info https://capacitorjs.com/docs/android/updating

this seems to work fine for me

@jimmy-cardenas-adl thx you very much

**Comment by SergioSuarezDev** [comment]
I have continue having the same problem, jetifier didn't solve it
