### ISSUE TITLE
Drop cordova-plugin-add-swift-support

### ISSUE THREAD

**Issue by l3ender** [NiklasMerz/cordova-plugin-fingerprint-aio#238]
Is the dependency on `cordova-plugin-add-swift-support` still required? Or does Cordova now support Swift without the use of this dependency/plugin?

If the latest versions of Cordova support Swift without this plugin, could we do a new major release dropping it from the dependency list?

Thanks!

**Comment by NiklasMerz** [comment]
@l3ender Thanks for the issues. Yes you are right. The plugin is no longer necessary with the latest version of cordova-ios. But we may need some changes. See #219 

Closing as duplicate
