### ISSUE TITLE
Archive fails on Xcode 11.4.1

### ISSUE THREAD

**Issue by jdelpr** [NiklasMerz/cordova-plugin-fingerprint-aio#239]
### Bug report
Hi all, I'm pretty new to iOS development and I get stuck for some days with the fingerprint-air plugin.

## Environment
I use Ionic v6.5.0. with capacitor and Xcode 11.4.1

## Description
When I add the fingerprint-aio using npm install cordova-plugin-fingerprint-aio, it builds ok in Xcode but when I try to make an Archive, I have 3 build errors with compiling swift:
- Inferred submodules require a module with an umbrella
- Umbrella for module 'CordovaPlugins' already covers this directory
- capacitor: compileSwift failed with a nonzero exit status.

## Logs
Here are the Archive results:
![image](https://user-images.githubusercontent.com/63952649/79689597-30751800-8256-11ea-99ae-ad234b435b46.png)

Here is my plist.info
![image](https://user-images.githubusercontent.com/63952649/79689560-f86dd500-8255-11ea-905e-787826b6c713.png)

In fact, fingerprint is the only swift plugin I have...

I tried dealing with the config.xml and adding cordova-plugin-add-swift-support without success. Maybe the solution is evident for you... Could you help me ?
Thanks,
Julien

**Comment by sardapv** [comment]
doc says u would  need latest xcode for it as default swift version is set to 4.0 so try doing it? @jdelpr

**Comment by NiklasMerz** [comment]
Exactly. Closing this as it is open for a while. 

But could also be a capacitor problem.
