### ISSUE TITLE
Obtain which authentication method was used to gain access ( FaceID or Fingerprint or Password)

### ISSUE THREAD

**Issue by shinz4u** [NiklasMerz/cordova-plugin-fingerprint-aio#240]
Obtain information on which authentication was used to gain access. 

I would like to know if the person used biometric authentication(i.e FaceID or Fingerprint) or password to gain access. 

Is there a way to know which method was used?

**Comment by shinz4u** [comment]
I am looking for both Android and iOS. 

isAvailable will provide us information regarding whether the authentication type is available right?

I am concerned more about the type the person used. 

For example, the user has FaceID, but cancelled it or maybe his FaceID authentication did not work and then used the fallback mechanism which is the pin or password to gain access. 

So whether I will be able to know whether the user used FaceID/ Fingerprint or the Fall back mechanism?

**Comment by NiklasMerz** [comment]
As far as I know we cannot get this from the API. On iOS at least.
