### ISSUE TITLE
FACE ID not working on android

### ISSUE THREAD

**Issue by Jhanzaibkhadim** [NiklasMerz/cordova-plugin-fingerprint-aio#244]
Hi All
i am getting the following response on infinix HOT 8 android
my fingerprint authentication is working fine but if i remove fingerprints and enrolled faceid on device than this is the response.
![Capture2](https://user-images.githubusercontent.com/17517075/82363718-a7edc100-9a27-11ea-8ec5-6610ca3baa50.PNG)

 
 
## Environment
![3](https://user-images.githubusercontent.com/17517075/82363810-c9e74380-9a27-11ea-8598-e069b7ea18ca.PNG)

* Plugin version
 "@ionic-native/fingerprint-aio": "^4.20.0",

**Comment by simon-moon** [comment]
having this same issue

**Comment by exxbrain** [comment]
duplicates #204
