### ISSUE TITLE
finger print aio issues with sencha extjs app

### ISSUE THREAD

**Issue by niteshtdcv** [NiklasMerz/cordova-plugin-fingerprint-aio#253]
### Bug report
I am using the plugin in my sencha Extjs app and getting the below issues.

1) After opening the app when we lock the mobile screen and again unlock the mobile device, the finger print screen on the app disappears.
2) Opening the app and toggling to another app and coming back to this app the finger print appears sometimes and disappears sometime.
3) On the app the , if we tap outside the fingerprint dialog on the app the finger print dialog disappears.
4) After 5 unsuccessful attempts the backup options like pin/pattern should open , but this is not happening.
5) The cancel button is not appearing in a white finger print dialog , but is the theme is changed to black it appears.

## Description

* What did you do?
 used the cordova aio plugin and getting the above issues.
* What did happen?
Issue mentioned in detail above
* What did you expect to happen?
This is not the actual behavior expected

## Environment

Node version: v12.18.0
Cordova version: 8.1.1

Config.xml file:

<?xml version='1.0' encoding='utf-8'?>
<widget id="com.tdcv.timebooking" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>FingerPrintDemo</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <plugin name="cordova-plugin-fingerprint-aio" spec="https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio.git" />
    <engine name="android" spec="^8.1.0" />
</widget>

Plugins:

cordova-plugin-fingerprint-aio,cordova-plugin-whitelist

### Logs

<details>
  <pre>[Please insert any logs here]</pre>
</details>

**Comment by NiklasMerz** [comment]
Hi I think most of this can be solved by app code or is something we cannot change in the plugin. I don't know Extjs and how this could affect this.

Are you talking about __Android or iOS__?

Let's get into this:

1. Please check your apps code if success or error callbacks are called. This behaviour is probably something the fingerprint API does by itself.
2. sane as above
3. This is probably up to the device you are using. This should not be possible on iOS. On Android the recent versions use some API that is called "Biometric Prompt". It's up to the device manufacturer how the prompt looks like. I have an OnePlus 6T and it does not show any prompt just the in-screen fingerprint icon and I can touch the whole screen and not close the fingerprint prompt. I would advise you to test different Android devices.
4. Did you allow backup? It should work like that on iOS. Not sure about all Android devices.
5, Same as 3. The dialogue is completely designed by the manufacturer.

**Comment by niteshtdcv** [comment]
Dear  Niklas, 

Thanks for your prompt reply.
Reply to your response : 

1. Success and error callbacks are done in the app.
  In our case when we are opening the app the finger print prompt appears,then we lock the mobile device. After unlocking the 
  device the fingerprint prompt on the app does not appear and the app becomes inactive .
  Expected Behavior - After unlocking the device, the fingerprint prompt should appear on the app and the user should be able 
  to continue using the app.
   
2. Same as above.

3.  In my device the popup screen is covering lower half of the mobile screen  . When tapping on the upper half of the device 
  screen , an alert popup "Authentication invalid BIOMETRIC_DISMISSED" is shown . On tapping 'OK' in the popup, the app 
  screen becomes active .
  Expected Behavior - The biometric popup should not get dismissed tapping anywhere outside the popup  and it is mandatory 
  for the user to provide biometric to use the app.

4. disableBackup is 'false' by default, i have not changed this parameter.
  Expected Behavior -  When the user inputs wrong fingerprint 5 times , the backup screen (pin/pattern) should appear.

Please let us know how we can achieve the expected behavior with this plugin ? 

Regards,
Nitesh

**Comment by NiklasMerz** [comment]
Some suggestions:

1. You should open the prompt again in the "resume event" https://cordova.apache.org/docs/en/dev/cordova/events/events.html#resume
2. same as above
3. As said this is not possible because the way the prompt works is created by the device manifacturer. We cannot change this in this plugin. We just use the Biometric Prompt API. You may find more options for that. Let me know.
4. Not sure how that works on different devices. See above.

**I still don't know if you are talking about Android or iOS.**

**Comment by niteshtdcv** [comment]
Hi Niklas, 

Sorry for the delay as we were trying all the possible options to get rid of the issues faced.
Device lock and unlock is dismissing the finger issue is still not resolved.

As suggested by you to use onResume event could help us to to resolve the issue , updating you on the options i have tried.

I have created a separate function for **Fingerprint.show** which i am calling in the **isAvailableSuccess**  in the launch function of my App. I am calling the same **Fingerprint.show** from onResume function . 
Opening the App for the first time with the fingerprint dialog on top .
When we lock the phone , the BIOMETRIC_DISMISSED is printed in console and hence the onResume function gets called in the App ,this is because the app moved to the foreground from background. 
As a result  **Fingerprint.show** gets called through the onResume  in the locked state of phone.
On phone unlock the fingerprint dialog is still not visible.

When we just make a console print in the onResume event , it gets called twice i.e. while locking and unlocking the device .But when the **Fingerprint.show** is called from onResume, the onResume event gets called only once (while device is locked).

Kindly suggest to get this issue resolved.

Regards,

Nitesh
