### ISSUE TITLE
How to use this plugin with a custom app?

### ISSUE THREAD

**Issue by vaibhav-jain** [NiklasMerz/cordova-plugin-fingerprint-aio#27]
## How to use this plugin with a custom app?

* I want to use this application with a custom application (Attendance app)
* How can I get the user FingerPrint data?? Not authentication
* Question?

## Environment

- Cordova CLI: 6.4.0 
- Ionic CLI Version: 2.1.18
- Ionic App Lib Version: 2.1.7
- ios-deploy version: Not installed
- ios-sim version: Not installed
- OS: Linux 4.4
- Node Version: v4.0.0
- Xcode version: Not installed

**Comment by NiklasMerz** [comment]
Hello

What do you want to do with the fingerprint? The plugin only accepts fingerprints which are enrolled via the device settings.

**Comment by NiklasMerz** [comment]
I am closing this now. If you have further questions, feel free to ask on [Gitter](https://gitter.im/cordova-plugin-fingerprint-aio)
