### ISSUE TITLE
Multiple Errors while gradle build

### ISSUE THREAD

**Issue by AtoLORIN** [NiklasMerz/cordova-plugin-fingerprint-aio#273]
### Bug report

![image](https://user-images.githubusercontent.com/26856078/93196531-db78f780-f74a-11ea-97af-02ec15a419ae.png)
![image](https://user-images.githubusercontent.com/26856078/93196615-f3e91200-f74a-11ea-9b3d-2e09945e050a.png)

Multiple Error in the BiometricAvtivity File, import errors 

## Description

Ionic4 with CAPACITOR ionic-native plugin Fingerprint AIO
(https://ionicframework.com/docs/native/fingerprint-aio),

npx cap open android

The Errors appear while gradle build

## Environment

@ionic/cli@6.11.8
cordova@10.0.0
cordova-res@0.14.0
native-run@1.0.0

### Logs

<details>
  <pre>Executing tasks: [:app:assembleDebug] in project C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android

> Configure project :app
+-----------------------------------------------------------------
| cordova-android-support-gradle-release: 27.+
+-----------------------------------------------------------------
google-services.json not found, google-services plugin not applied. Push Notifications won't work

> Configure project :capacitor-cordova-android-plugins
+-----------------------------------------------------------------
| cordova-android-support-gradle-release: 27.+
+-----------------------------------------------------------------

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :capacitor-android:preBuild UP-TO-DATE
> Task :capacitor-android:preDebugBuild UP-TO-DATE
> Task :capacitor-android:compileDebugAidl NO-SOURCE
> Task :capacitor-cordova-android-plugins:preBuild UP-TO-DATE
> Task :capacitor-cordova-android-plugins:preDebugBuild UP-TO-DATE
> Task :capacitor-cordova-android-plugins:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :capacitor-android:packageDebugRenderscript NO-SOURCE
> Task :capacitor-cordova-android-plugins:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig
> Task :app:javaPreCompileDebug
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :capacitor-android:generateDebugResValues
> Task :capacitor-android:compileDebugRenderscript NO-SOURCE
> Task :capacitor-android:generateDebugResources
> Task :capacitor-android:packageDebugResources
> Task :capacitor-cordova-android-plugins:generateDebugResValues
> Task :capacitor-cordova-android-plugins:compileDebugRenderscript NO-SOURCE
> Task :capacitor-cordova-android-plugins:generateDebugResources
> Task :capacitor-cordova-android-plugins:packageDebugResources
> Task :app:createDebugCompatibleScreenManifests
> Task :app:extractDeepLinksDebug
> Task :capacitor-android:extractDeepLinksDebug
> Task :capacitor-cordova-android-plugins:extractDeepLinksDebug
> Task :app:mergeDebugResources
> Task :capacitor-cordova-android-plugins:processDebugManifest
> Task :capacitor-android:processDebugManifest
> Task :app:processDebugManifest
> Task :capacitor-android:compileDebugLibraryResources
> Task :capacitor-android:parseDebugLocalResources
> Task :capacitor-cordova-android-plugins:compileDebugLibraryResources
> Task :capacitor-cordova-android-plugins:parseDebugLocalResources
> Task :capacitor-android:generateDebugRFile
> Task :capacitor-cordova-android-plugins:generateDebugRFile
> Task :app:processDebugResources
> Task :capacitor-android:generateDebugBuildConfig
> Task :capacitor-android:javaPreCompileDebug

> Task :capacitor-android:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :capacitor-cordova-android-plugins:generateDebugBuildConfig
> Task :capacitor-cordova-android-plugins:javaPreCompileDebug
> Task :capacitor-android:bundleLibCompileToJarDebug

> Task :capacitor-cordova-android-plugins:compileDebugJavaWithJavac FAILED
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:10: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:11: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:12: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;
                                 ^
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:13: error: package android.support.v7.app does not exist
import android.support.v7.app.AppCompatActivity;
                             ^
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:19: error: cannot find symbol
public class BiometricActivity extends AppCompatActivity {
                                       ^
  symbol: class AppCompatActivity
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:25: error: cannot find symbol
    protected void onCreate(@Nullable Bundle savedInstanceState) {
                             ^
  symbol:   class Nullable
  location: class BiometricActivity
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:116: error: cannot find symbol
    private void onError(int errorCode, @NonNull CharSequence errString) {
                                         ^
  symbol:   class NonNull
  location: class BiometricActivity
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:24: error: method does not override or implement a method from a supertype
    @Override
    ^
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:26: error: cannot find symbol
        super.onCreate(savedInstanceState);
        ^
  symbol:   variable super
  location: class BiometricActivity
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:28: error: cannot find symbol
        setTitle(null);
        ^
  symbol:   method setTitle(<null>)
  location: class BiometricActivity
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:30: error: cannot find symbol
                .getIdentifier("biometric_activity", "layout", getPackageName());
                                                               ^
  symbol:   method getPackageName()
  location: class BiometricActivity
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:29: error: cannot find symbol
        int layout = getResources()
                     ^
  symbol:   method getResources()
  location: class BiometricActivity
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:31: error: cannot find symbol
        setContentView(layout);
        ^
  symbol:   method setContentView(int)
  location: class BiometricActivity
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:37: error: cannot find symbol
        mPromptInfo = new PromptInfo.Builder(getIntent().getExtras()).build();
                                             ^
  symbol:   method getIntent()
  location: class BiometricActivity
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:47: error: no suitable constructor found for BiometricPrompt(BiometricActivity,Executor,AuthenticationCallback)
                new BiometricPrompt(this, executor, mAuthenticationCallback);
                ^
    constructor BiometricPrompt.BiometricPrompt(FragmentActivity,Executor,AuthenticationCallback) is not applicable
      (argument mismatch; BiometricActivity cannot be converted to FragmentActivity)
    constructor BiometricPrompt.BiometricPrompt(Fragment,Executor,AuthenticationCallback) is not applicable
      (argument mismatch; BiometricActivity cannot be converted to Fragment)
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:68: error: cannot find symbol
                public void onAuthenticationError(int errorCode, @NonNull CharSequence errString) {
                                                                  ^
  symbol: class NonNull
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:74: error: cannot find symbol
                public void onAuthenticationSucceeded(@NonNull BiometricPrompt.AuthenticationResult result) {
                                                       ^
  symbol: class NonNull
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:88: error: cannot find symbol
        KeyguardManager keyguardManager = ContextCompat
                                          ^
  symbol:   variable ContextCompat
  location: class BiometricActivity
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:97: error: cannot find symbol
            this.startActivityForResult(intent, REQUEST_CODE_CONFIRM_DEVICE_CREDENTIALS);
                ^
  symbol: method startActivityForResult(Intent,int)
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:105: error: method does not override or implement a method from a supertype
    @Override
    ^
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:144: error: cannot find symbol
        setResult(RESULT_OK);
                  ^
  symbol:   variable RESULT_OK
  location: class BiometricActivity
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:145: error: cannot find symbol
        finish();
        ^
  symbol:   method finish()
  location: class BiometricActivity
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:156: error: cannot find symbol
        setResult(RESULT_CANCELED, data);
                  ^
  symbol:   variable RESULT_CANCELED
  location: class BiometricActivity
C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java:157: error: cannot find symbol
        finish();
        ^
  symbol:   method finish()
  location: class BiometricActivity
Note: C:\Users\Antoine\Desktop\Lucas Coco\petit projet\geolocApp\android\capacitor-cordova-android-plugins\src\main\java\de\niklasmerz\cordova\biometric\BiometricActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
24 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':capacitor-cordova-android-plugins:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
29 actionable tasks: 29 executed
</pre>
</details>

**Comment by AtoLORIN** [comment]
Finally i've found that i haven't the last version of the library and the new version fix my issue. Thanks You and sorry for this useless issue

**Comment by abhishek3365** [comment]
hello @AtoLORIN, I am facing the same issue. I have the latest version of the plugin installed( v3.0.1 ). What version are you using?

**Comment by AtoLORIN** [comment]
Hey @abhishek3365 , I'm not an experte of npm so i don't know how to upgrade to the new version... But I've fix my issue by modifying the source, you just have to replace the 4 imports like on the screen line 10 to 13 =>
![image](https://user-images.githubusercontent.com/26856078/93451054-f8dacc80-f8d6-11ea-830c-f80575ccd40f.png)

Hope this will help you :)

**Comment by edthenet** [comment]
I have installed version 4.0.1 and still have the same issue. I went back to version 3.0.1 and still have a broken app

**Comment by NiklasMerz** [comment]
Please use the latest version of the plugin.

For more issues like this and support please go to discussions.
