### ISSUE TITLE
Integration of Keychain(iOS) and KeyStore(android)

### ISSUE THREAD

**Issue by sardapv** [NiklasMerz/cordova-plugin-fingerprint-aio#274]
### Feature Request
Please add support for saving form credentials binded to touchid/faceid registered using a secure keychain on ios and keystore on android

#### Feature Description
There is existing old not at all maintained version available named 'cordova-plugin-keychain-touchid' . I Know many of us expects to have this feature as not always authentication is done by our registered thumb or face. 

Say for e.g I have a login form with 3 fields I want to use it next time to login (submit form) fetch credentials from keychain and boom login...

**Comment by leolio86400** [comment]
I think this is what this PR is doing https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/pull/236

**Comment by sardapv** [comment]
> I think this is what this PR is doing #236

You are doing great job! thank you, when can we expect the changes in release?

**Comment by NiklasMerz** [comment]
Release is about to come. Please test and report issues.
