### ISSUE TITLE
Using ionic4 FingerprintAuth is not defined

### ISSUE THREAD

**Issue by satish7475** [NiklasMerz/cordova-plugin-fingerprint-aio#288]
TypeError: Object(…) is not a function while using fingerprint plugin in ionic 4

Reference :Fingerprint AIO Plugin

this.fingerprintOptions = {
      title: 'Biometric Authentication', // (Android Only) | optional | Default: "<APP_NAME> Biometric Sign On"
      subtitle: 'Coolest Plugin ever', // (Android Only) | optional | Default: null
      description: 'Please authenticate', // optional | Default: null
      fallbackButtonTitle: 'Use Backup', // optional | When disableBackup is false defaults to "Use Pin".
      disableBackup:false,     // When disableBackup is true defaults to "Cancel"
      // clientId: 'Fingerprint-Demo',
      // clientSecret: 'password', //Only necessary for Android
      // disableBackup:false,  //Only for Android(optional)
      // localizedFallbackTitle: 'Use Pin', //Only for iOS
      // localizedReason: 'Please authenticate' //Only for iOS
       
  }
  try{
    const ava = await this.fingerAuth.isAvailable();
    debugger
    if(ava)
    {
      const res = await this.fingerAuth.show(this.fingerprintOptions);
      console.log(res);
    }
  
  }catch(e){
  
      console.log(e);
  
  }

**Comment by vivascau** [comment]
Hi, can you send the full error message and how you instantiate `this.fingerAuth`? 
It looks like it could be an error with your setup and maybe how you are defining fingerAuth ? Are you using `FingerprintAIO` ?  FingerprintAuth does not exist in this repo.

**Comment by NiklasMerz** [comment]
Exactly like @vivascau said. This is more likely an ionic-native problem. You also need to import in app.module.ts
