### ISSUE TITLE
Capacitor project build failed..Cyclic dependency in module 'CordovaPlugins': CordovaPlugins -> GSSDK 

### ISSUE THREAD

**Issue by yogeshezest** [NiklasMerz/cordova-plugin-fingerprint-aio#290]
## Description

* What did you do?
* What did happen?
* What did you expect to happen?

## Environment

* Plugin version
* Build environment (```cordova info```)
* ```cordova platform ls```

### Logs
 error: could not build module 'GSSDK'
#import <GSSDK/GSKPDFGeneratorError.h>
        ^
<unknown>:0: error: could not build Objective-C module 'CordovaPlugins'
<details>
  <pre>[Cyclic dependency in module 'CordovaPlugins': CordovaPlugins -> GSSDK -> CordovaPlugins </pre>
</details>

**Comment by NiklasMerz** [comment]
I do not think this is a problem of this plugin. This import is not part of this plugins source code. Please check for other plugins. Pressumably a PDF Generator from a simple Google search.
