### ISSUE TITLE
Is there a reason for not supporting cordova-android 8 version? (question)

### ISSUE THREAD

**Issue by pcsantana** [NiklasMerz/cordova-plugin-fingerprint-aio#292]
I have an app that still needs to support Android version 5.0
The cordova-android 9 dropped support for version 5.0, the minimum now is 5.1.

I tried to change in the plugin.xml to
`<engine name = "cordova-android" version = ">= 8.0.0" />`
and apparently it worked without problems.

Is there a reason for not supporting cordova-android 8?

Thank you very much for the great work and excellent plugin.

**Comment by NiklasMerz** [comment]
Yes the latest version of the plugin uses AndroidX which was made possible with Cordova Android 9. You can still use the older versions.

I am sorry but I did not look into making this available to older versions, yet. Feel free to do some tests and comment here.

**Comment by cremfert** [comment]
@pcsantana Did the plugin work without any issues when patching the plugin.xml? I have the same requirements like you (support old android versions), so I'm thinking of patching it. Or is it better to use an older version of the plugin that is compatible with cordova-android 8?

Thanks!

**Comment by pcsantana** [comment]
Hi @cremfert !

Yes, I have 2 apps in production that works without any problem.
If you want to try it, you can install a forked project that I created with this changes:

https://github.com/pcsantana/cordova-plugin-fingerprint-aio

It's important to say that as Niklas mentioned, the lastest version of the plugin uses AndroidX. So, you will need to install 2 great helpful additional plugins that help with it:

https://github.com/dpa99c/cordova-plugin-androidx
https://github.com/dpa99c/cordova-plugin-androidx-adapter

I hope helped you.

**Comment by cremfert** [comment]
Dear @pcsantana,

thanks a lot - I already have the two mentioned plugins installed as other plugins need them as well. Great to hear that the plugin is working flawlessly with the changes.
