### ISSUE TITLE
Is there any possibility to customise the fingerprint dialog ?

### ISSUE THREAD

**Issue by bhargavas12** [NiklasMerz/cordova-plugin-fingerprint-aio#316]
Right now the plugin is supporting the system default fingerprint dialog.
Is there any way to customize the fingerprint dialog (we need the fingerprint dialog in center of the screen for all the devices) ?

**Comment by NiklasMerz** [comment]
No this is not possible and probably never will be part of this plugin. The goal of this plugin is to use the native APIs as much as possible.

**Comment by bhargavas12** [comment]
Can we update the styles for the text (change color for description, title) in the fingerprint dialog?

**Comment by NiklasMerz** [comment]
Unfortunately not. We just pass information to the OS.

**Comment by bhargavas12** [comment]
okay thanks
