### ISSUE TITLE
Missing dependency error in @ionic-native/core

### ISSUE THREAD

**Issue by westabilife** [NiklasMerz/cordova-plugin-fingerprint-aio#324]
### Bug report
Error Reported while making build in ionic 6.12.4

## Description

* What did you do?
* What did happen?
* What did you expect to happen?

## Environment

* Plugin version
* Build environment (```cordova info```)
* ```cordova platform ls```

### Logs

<details>
  <pre>C:\power house\myApp>ionic cordova build android
> ng.cmd run app:ionic-cordova-build --platform=android
√ Browser application bundle generation complete.

Error: The target entry-point "@ionic-native/fingerprint-aio" has missing dependencies:
 - @ionic-native/core

[ERROR] An error occurred while running subprocess ng.

        ng.cmd run app:ionic-cordova-build --platform=android exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

C:\power house\myApp></pre>
</details>

**Comment by NiklasMerz** [comment]
Please use `npm install @ionic-native/core`. This is not an issue of this plugin but ionic-native.
