### ISSUE TITLE
Issue with closing brace

### ISSUE THREAD

**Issue by ajnrajeev** [NiklasMerz/cordova-plugin-fingerprint-aio#33]
## Description
The merge commit for fix-passcode with ios-localized-reason removed one closing brace. Hence causing an issue.

* What did you do?
Pulled new plugin
* What did happen?
evaluate policy is not happening
* What did you expect to happen?
Native popup to chow
* Type of issue (bug, feature request)
bug

## Environment

* Plugin version 1.2.
* Build environment (```cordova info```)
* ```cordova platform ls```
ios

**Comment by ajnrajeev** [comment]
@NiklasMerz, I have created a pull request to fix the same. Please do check on priority.

**Comment by NiklasMerz** [comment]
@ajnrajeev Thanks for reporting and fixing this. I will publish bugfix version on npm now
