### ISSUE TITLE
Setting swift version to v4 in plugin

### ISSUE THREAD

**Issue by PavelLapkoG** [NiklasMerz/cordova-plugin-fingerprint-aio#342]
#### Feature Description
You are setting 4 version in plugin.xml. But in our project we have  4.2 UseSwiftLanguageVersion and have plugins (cordova-plugin-qrscanner for example) which use new version methods (UIApplication.openSettingsURLString), so as result we have fail on build. Do you have any ideas how solve this problem better? Thank you.

**Comment by dmitry-salnikov** [comment]
Same problem. This setting should be specified on per-project level, in `config.xml`. @exxbrain @leolio86400 could you please remove that?

**Comment by leolio86400** [comment]
We should still require 4+, not sure how to do that and very little time to investigate. Maybe you could put a PR in ?

**Comment by dmitry-salnikov** [comment]
@leolio86400 is it ok to simply update it to latest swift version - 5? if so, I'll make a one-line PR

**Comment by leolio86400** [comment]
Not really a good solution either you would then block everyone that are on swift < 5.
I am pretty sure there is a way to make a minimal requirement instead of strict number

**Comment by dmitry-salnikov** [comment]
> I am pretty sure there is a way to make a minimal requirement instead of strict number
I'm not sure. AFAIK swift version could be specified in either `config.xml` via `UseSwiftLanguageVersion`, or in any plugin's `plugin.xml` the same way it is done in this plugin. `config.xml` and `plugin.xml` settings are applied subsequently and by plain replacement, there's no any logic comparing specified versions and using minimum/maximum of them.

**Comment by NiklasMerz** [comment]
Thank your for reporting the issue. Please test the lates version 5.0.0 and make sure to add the version for config.xml
