### ISSUE TITLE
Fingerprint modal closes on authentication failed

### ISSUE THREAD

**Issue by mayankkataria** [NiklasMerz/cordova-plugin-fingerprint-aio#345]
When I authenticate with wrong finger I get an error with ```code=-102``` and ```message="Authentication failed"```. My problem is that fingerprint modal, instead of remaining open, closes itself automatically when this error is generated. I was not facing this issue in my older project. In that project, the modal remains open even when authentication fails and asks for another attempt. I think there's some issue with the native code in the latest version because the code which I'm using to implement this plugin is completely same in both the projects.

My code:
```
try {
      await this.plt.ready();
      const available = await this.faio.isAvailable();
      if (this.plt.is('android') && available === 'biometric') {
        const result = await this.faio.show(this.fOptions);
        if (result === 'biometric_success') {
          this.cancel();
        } else {
          console.log('bio unsuccess: ', result);
        }
    }
    } catch (error) {
      console.log('error: ', error);
      if (error.code === -102) { // Authentication failed
        // The fingerprint modal is closing itself
      }
    }
```

Old project configuration (with no issue):
```
"@ionic-native/fingerprint-aio": "^5.27.0",
"cordova-plugin-fingerprint-aio": "^3.0.1"
```

New project configuration (modal closes on authentication failed):
```
"@ionic-native/fingerprint-aio": "^5.31.1",
"cordova-plugin-fingerprint-aio": "^4.0.2"
```

**Comment by cyfras** [comment]
Any solution to this

**Comment by seamlink-aalves** [comment]
I see the same problem in my app.

**Comment by levanax** [comment]
Is there any solution

**Comment by rishav-goyal** [comment]
Same issue I am also facing, it should give message not match and remain open but it is getting close every time.

**Comment by FlorinSerban** [comment]
Hello,

Has anyone found a solution for this?

**Comment by levanax** [comment]
> 

no!  i have given up using this plugin

**Comment by seamlink-aalves** [comment]
I've created a PR to solve this issue. It's working for me. Let's hope this gets merged.

**Comment by NiklasMerz** [comment]
We previously implemented this as expected behaviour https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/issues/247. I need to test and research this more.

**Comment by seamlink-aalves** [comment]
The behaviour I get is that when using fingerprint sometimes the answer received by the plugin is that the authentication failed. 

By returning the plugin error the cordova activity ends. If we do not return the error the activity does not end and the user is given another opportunity to authenticate. 

The user can still cancel.
