### ISSUE TITLE
"export 'Cordova' was not found in '@ionic-native/core'

### ISSUE THREAD

**Issue by CSCMML** [NiklasMerz/cordova-plugin-fingerprint-aio#368]
i have a issue... that say me "export 'Cordova' was not found in '@ionic-native/core'

 "@ionic-native/core": "^5.36.0",
 "@ionic-native/fingerprint-aio": "^4.20.0",

**Comment by NiklasMerz** [comment]
This is most likely an issue with ionic native. Please report or fix here: https://github.com/ionic-team/ionic-native
