### ISSUE TITLE
Android API 30 - Changed canAuthenticate()

### ISSUE THREAD

**Issue by sonnylloyd** [NiklasMerz/cordova-plugin-fingerprint-aio#369]
## Description

The android plugin does not work with android API 30 (android 11). Google are now forcing new apps to target API 30 from the 2nd august 2021. 

The original call that is used by this plugin has been deprecated
`canAuthenticate ()`
Authenticators now have to be specified
`canAuthenticate(int authenticators)
`
see the following
https://developer.android.com/reference/android/hardware/biometrics/BiometricManager

**Comment by sonnylloyd** [comment]
Im not entirely sure if this is the case.

When i compile and run the app from android studio it works fine (my phone is android 10 API 29). 

But when i sign it and upload it for internal testing the biometric dialog does not show. 

it did initially work but google has forced me to use api 30 going forward and it no longer shows. 

This is the only change i can think of that would cause the problem. I have also forked this project and tried to add the work to upgrade the call to the api 30 version canAuthenticate(int) without much success (it has been 9 years since i have touched android java so im very rusty).

**Comment by sonnysunzu** [comment]
For anyone else having this issue. Its not the plugin or api version its R8 / proguard shrinking * obfuscating the code.
