### ISSUE TITLE
iOS disableBackup option

### ISSUE THREAD

**Issue by inexuscore** [NiklasMerz/cordova-plugin-fingerprint-aio#38]
Feature Request
==========

I'm using Cordova 6.x and Ionic 1.3.2 on a Android 6 device.
How can I disable backup authentication for both iOS and Android?

If Fingerprint/Touch ID is available (hardware detected and enrolled) I want users to authenticate. Otherwise or if users cancel, they shouldn't be able to use a backup plan (i.e. PIN confirmation). I want to required  fresh sign in.

Cheers, and thanks for the repo!

**Comment by NiklasMerz** [comment]
You can call open with the disable backup parameter. Like this:

```
Fingerprint.show({
      clientId: "Fingerprint-Demo",
      clientSecret: "password",
      disableBackup: true
    }, successCallback, errorCallback);
```

**Comment by NiklasMerz** [comment]
I am closing this for now. If you have any questions please ask me on [Gitter](https://gitter.im/cordova-plugin-fingerprint-aio). If this is an issue and not a question, feel free to open this again.
