### ISSUE TITLE
Unsupported Swift Version

### ISSUE THREAD

**Issue by TF-Jonny** [NiklasMerz/cordova-plugin-fingerprint-aio#382]
When adding the plugin xcode throws a message stating that 'The target "app_name" contains source code developed with Swift 3.x. This version of Xcode does not support building or migrating Swift 3.x targets. Use Xcode 10.1 to migrate the code to Swift 4.'

Due to been on the latest version of Mac I'm unable to install Xcode 10.1 to do the migration.

macOS Monterey 12.0.1
Xcode 13.1
cordova-ios 6.2.0
cordova-plugin-fingerprint-aio 4.0.2

When I remove the plugin no error message when loading Xcode, moment I add the plugin back in the error message returns.

**Comment by CaioMelo8** [comment]
Related issues #335 and #342.

**Comment by NiklasMerz** [comment]
Thank your for reporting the issue. Please test the lates version 5.0.0 and make sure to add the version for config.xml

**Comment by TF-Jonny** [comment]
I managed to get it to work with version 4.0.2 by just removing the swift version from the config. But good to hear its fixed in lastest build also.
