### ISSUE TITLE
Enter password if the fingerprint fails

### ISSUE THREAD

**Issue by alvarheras** [NiklasMerz/cordova-plugin-fingerprint-aio#40]
## Description

Hello

First of all, congratulations on the plugin.

I have detected that I have a problem in IOS when the user badly inserts the fingerprint, when this happens a popup opens where you can give a password or a password to access or cancel.

![captura](https://user-images.githubusercontent.com/11508953/28450396-6b081e9e-6de7-11e7-9923-5e3338c33654.PNG)

When I press on enter password, the application does not respond to this call, it would have to show the pattern or password.

Thax 👍 

## Environment

IOS devices

**Comment by NiklasMerz** [comment]
Which version of the fingerprint plugin are you using? I recently published a bugfix which addresses this issue.

**Comment by alvarheras** [comment]
ouch yes sorry is working good with last version 👍
