### ISSUE TITLE
Can't install from `cordova plugin add cordova-plugin-fingerprint-aio --save`

### ISSUE THREAD

**Issue by sumodevelopment** [NiklasMerz/cordova-plugin-fingerprint-aio#41]
## Description

* I ran the command `cordova plugin add cordova-plugin-fingerprint-aio --save` in the root of my ionic project.
* The plugin could not install and returned the error: 
```
Failed to install 'cordova-plugin-fingerprint-aio': Error
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:205:33
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:864:24)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:890:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:808:41)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Error: Failed to fetch plugin cordova-plugin-add-swift-support via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/cordova-plugin-add-swift-support" as it does not contain a package.json file.
```
* Expected a successful install of package.
* TYPE: Bug

## Environment

* Latest version
* Build environment 
 ```
Node version: v8.2.1
Cordova version: 7.0.1

Plugins: 

cordova-plugin-console,cordova-plugin-device,cordova-plugin-fingerprint-aio,cordova-plugin-splashscreen,cordova-plugin-statusbar,cordova-plugin-whitelist,de.appplant.cordova.plugin.printer,ionic-plugin-keyboard,phonegap-nfc

iOS platform:

Xcode 8.3.3
Build version 8E3004b
```

### Logs
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.2.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'cordova-plugin-add-swift-support',
1 verbose cli   '--save' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose npm-session 8284515a6cb789c5
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for cordova-plugin-add-swift-support@file:node_modules/cordova-plugin-add-swift-support Could not install from "node_modules/cordova-plugin-add-swift-support" as it does not contain a package.json file.
8 verbose stack Error: ENOENT: no such file or directory, open '/Volumes/Mercury/Development/testing/c-series-demo/node_modules/node_modules/cordova-plugin-add-swift-support/package.json'
9 verbose cwd /Volumes/Mercury/Development/testing/c-series-demo/node_modules
10 verbose Darwin 16.6.0
11 verbose argv "/usr/local/Cellar/node/8.2.1/bin/node" "/usr/local/bin/npm" "install" "cordova-plugin-add-swift-support" "--save"
12 verbose node v8.2.1
13 verbose npm  v5.3.0
14 error code ENOLOCAL
15 error Could not install from "node_modules/cordova-plugin-add-swift-support" as it does not contain a package.json file.
16 verbose exit [ 1, true ]

```

**Comment by NiklasMerz** [comment]
Hi @sumodevelopment 

Thanks for submitting this report. From your logs I can see that you are using NodeJs 8+. I personally had problems with Cordova and NodeJs 8. So I decided to install NodeJs 6.x LTS and since then Cordova works fine again. I would suggest you to try downgrading NodeJs. 

Since this is more a support request at the moment, I am closing this issue for now. If you have any questions please contact me on [Gitter](https://gitter.im/cordova-plugin-fingerprint-aio). If this should be a problem with this plugin, feel free to open the issue again.

**Comment by sumodevelopment** [comment]
Thanks! I'll do just that.

**Comment by samastur** [comment]
I get this error with NodeJS v6.11.3

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'cordova-plugin-add-swift-support',
1 verbose cli   '--save' ]
2 info using npm@5.4.2
3 info using node@v6.11.3
4 verbose npm-session be72c463685ae35d
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for cordova-plugin-add-swift-support@file:node_modules/cordova-plugin-add-swift-support Could not install from "node_modules/cordova-plugin-add-swift-support" as it does not contain a package.json file.
8 verbose stack Error: ENOENT: no such file or directory, open '/Users/markos/work/klevio/klevio-app/node_modules/node_modules/cordova-plugin-add-swift-support/package.json'
8 verbose stack     at Error (native)
9 verbose cwd /Users/markos/work/klevio/klevio-app/node_modules
10 verbose Darwin 16.7.0
11 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "cordova-plugin-add-swift-support" "--save"
12 verbose node v6.11.3
13 verbose npm  v5.4.2
14 error code ENOLOCAL
15 error Could not install from "node_modules/cordova-plugin-add-swift-support" as it does not contain a package.json file.
16 verbose exit [ 1, true ]

**Comment by NiklasMerz** [comment]
Please try adding the swift support plugin manually. I have recieved some reports about issue with this plugin while installing.

**Comment by samastur** [comment]
Yup, if I manually add swift support then install works.

**Comment by iamAloTheGreat** [comment]
Hi. I also encounter the same problem. Just want to ask, how can I add the swift support manually? @samastur

**Comment by NiklasMerz** [comment]
`cordov plugin add https://github.com/akofman/cordova-plugin-add-swift-support.git`

I have no idea why adding the dependency doesnt work.

**Comment by iamAloTheGreat** [comment]
Hi @NiklasMerz I got the following errors when I entered 
`cordova plugin add https://github.com/akofman/cordova-plugin-add-swift-support.git`

```
Error: Failed to fetch plugin https://github.com/akofman/cordova-plugin-add-swift-support.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 194 Error output:
npm WARN checkPermissions Missing write access to /Users/aloimmaculata/Documents/Sushi Joint latest Project/SushiJoint/node_modules/cordova-plugin-add-swift-support
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path /Users/aloimmaculata/Documents/Sushi Joint latest Project/SushiJoint/node_modules/cordova-plugin-add-swift-support
npm ERR! code ELOOP
npm ERR! errno -62
npm ERR! syscall access
npm ERR! ELOOP: too many symbolic links encountered, access '/Users/aloimmaculata/Documents/Sushi Joint latest Project/SushiJoint/node_modules/cordova-plugin-add-swift-support'

┌──────────────────────────────────────────────────────────────────┐
│                     npm update check failed                      │
│               Try running with sudo or get access                │
│               to the local update config store via               │
│ sudo chown -R $USER:$(id -gn $USER) /Users/aloimmaculata/.config │
└──────────────────────────────────────────────────────────────────┘

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aloimmaculata/.npm/_logs/2017-09-24T13_39_08_010Z-debug.log
```

**Comment by NiklasMerz** [comment]
Like the error log says, it is a write problem on your machine.

**Comment by iamAloTheGreat** [comment]
I added the folder from the `https://github.com/akofman/cordova-plugin-add-swift-support.git` to the folder node_modules then installation works fine. :) I hope it will not give any problems in the future and  I hope adding the dependency will be fix in the future. :) Thank you this solved my problem.

**Comment by iamAloTheGreat** [comment]
Hello again. What is the applicable way of downgrading the nodejs to the version you are suggesting @NiklasMerz ? I'm using Mac and currently, NodeJs v8.2.1 is being installed. I received an error when testing to an actual device. Thanks in advance. :)

**Comment by NiklasMerz** [comment]
I will check NodeJS 8 out.

**Comment by iamAloTheGreat** [comment]
Okay and thanks @NiklasMerz . 
Btw, I found out that the latest Cordova7 is now asking package.json file on every plugin thats why the error appeared.
See https://cordova.apache.org/news/2017/05/04/cordova-7.html
What I did for the mean time, I downgraded my Cordova to Cordova6 and nodeJS to v6.11.3 (lts)

Additionally, I tried to update the plugin version to 1.2.2 (which is stated in the Pull Requests)  but it says that the latest version is 1.2.1. Will you please confirm this.

**Comment by NiklasMerz** [comment]
Thanks for finding this out. Maybe you should create an issue in the swift support repo?

The current version on npm is 1.2.1. I will sort the versioning put in the coming days
