### ISSUE TITLE
Does this support FaceID on Capacitor?

### ISSUE THREAD

**Issue by teacoat** [NiklasMerz/cordova-plugin-fingerprint-aio#432]
Same as title, does faceID on iOS work on capacitor? If so, how to install it with the flags?

**Comment by NiklasMerz** [comment]
With capacitor you need to set the `FACEID_USAGE_DESCRIPTION` yourself in Info.plist.

**Comment by teacoat** [comment]
@NiklasMerz thank you - one more question, can I use this without ionic?

**Comment by NiklasMerz** [comment]
Yes sure. You can use capacitor without Ionic. Just use the normal Javascript API of this plugin.
