### ISSUE TITLE
isAvailable is not a function

### ISSUE THREAD

**Issue by mitchn5** [NiklasMerz/cordova-plugin-fingerprint-aio#439]
Hi, I've been trying to use isAvailable function in order to check before showing a button to call show(). Show function works but when calling isAvailable I just get a does not exist error. Any ideas? this is the code I have for now

window.Fingerprint.isAvailable((result: any) => {
  console.log("in isAvailable success, returning true");
  return true;
}, (error: any) => {
  alert(error.message);
});

**Comment by mitchn5** [comment]
Hi Guys, any idea what's going on here?

**Comment by NiklasMerz** [comment]
Are you waiting for the deviceReady event?

**Comment by mitchn5** [comment]
Yes we found a solution similar to this, thank you.
