### ISSUE TITLE
Custom pop up

### ISSUE THREAD

**Issue by maxborgatti** [NiklasMerz/cordova-plugin-fingerprint-aio#44]
i'm submitting a feature request

![image](https://user-images.githubusercontent.com/8874135/29705185-2e0b3a4c-897d-11e7-856f-8196a2832f80.png)

what if someone needs to let pop up a custom message/div/template while waiting for user fingerprint?

the plugin is super easy and very well working, and this is a huge limitation e.g. for other countries, or companies asking for custom layouts

**Comment by NiklasMerz** [comment]
Hi thank you for submitting this request.

Are you talking about Android? You are right. The Android implementation lacks this feature. For iOS it is possible to add  a custom message.

**Comment by maxborgatti** [comment]
Thank you for your super quick feedback!

I think about a fully custom layout. E.G. an option to silent default alert and launch a custom event (a modal), and another custom event (dismiss?) on success/error events

**Comment by NiklasMerz** [comment]
This sounds interessting. But right now I don´t have an idea how to do a fully customizable layout since the prompt is called natively. Android and iOS give recommendations how a fingerprint prompt should look like. On Android there is room to cutomize the desing but iOS only supports the built-in prompt as far as I know.

**Comment by maxborgatti** [comment]
Yes, i'm sorry, i did take a deep look and notice that only Android allows customs.

What if i would like to anyway hard-code-customize the plugin Android prompt layout?

Thanks in advance for your cooperation

**Comment by NiklasMerz** [comment]
You could customize the layout and strings in the XML files in the res folder of your local plugin installation. Maybe customization will be added later in some form.

**Comment by maxborgatti** [comment]
thanks, everything's clear!
