### ISSUE TITLE
Plugin is not working if fingerprint is not supported in device

### ISSUE THREAD

**Issue by siraj-coder** [NiklasMerz/cordova-plugin-fingerprint-aio#448]
When we try to integrate AIO plugin with our app it is giving error as **hardware not supported** , as my device does not support fingerprint but it supports face id and pin. Can we integrate this plugin with my app as only face id or pin authentication?

Currently my app is built on :

Android version: 11
Ionic version: 5.36.x
Angular version: 12.2.x

**Comment by NiklasMerz** [comment]
Let's keep this in discussions for now.
