### ISSUE TITLE
Support Android Server authentication

### ISSUE THREAD

**Issue by NiklasMerz** [NiklasMerz/cordova-plugin-fingerprint-aio#45]
https://android-developers.googleblog.com/2015/10/new-in-android-samples-authenticating.html

**Comment by ocReaper** [comment]
The original plugin that you (@NiklasMerz) used as a base, already fixed this random response behavior. Please see (issue 5)[https://github.com/mjwheatley/cordova-plugin-android-fingerprint-auth/issues/5] for more information.

**Comment by NiklasMerz** [comment]
I don't think this feature is still relevant. The new API in #129 will bring some changes.
