### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by amirwolf5122** [NiklasMerz/cordova-plugin-fingerprint-aio#458]
[This package](https://www.jsdelivr.com/package/npm/cordova-plugin-fingerprint-aio) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by NiklasMerz** [comment]
I am just curious why is this necessary and why did you file this issue? This package is usually only used with Cordova and it doesn't need this.
