### ISSUE TITLE
IOs Bypass Code Injection

### ISSUE THREAD

**Issue by Lindsor** [NiklasMerz/cordova-plugin-fingerprint-aio#471]
### Summary
Through code injection malicious user can change the `result` of `authenticate` from `false` to `true` and thus trick the consuming application into thinking the biometric authentication was successful.

### Details
I'm honestly not sure if there is a solution for this or not. My enterprises PenTest team flagged this finding but I cant find any indication there is a true solution for it.

The finding indicates that the plugin uses the `evaluatePolicy()` methods `True|False` response which can be modified by code injection by using a Frida script or through a library such as objection (https://github.com/sensepost/objection).

After doing some research I don't think there is a solution for this, `evaluatePolicy()` is the solution provided by Apple and is further ratified by OWASP:
https://mas.owasp.org/MASTG/iOS/0x06f-Testing-Local-Authentication/
According to the OWASP link above this is a known limitation:

> Please be aware that using either the LocalAuthentication.framework or the Security.framework, will be a control that can be bypassed by an attacker as it does only return a boolean and no data to proceed with. See [Don't touch me that way, by David Lindner et al ↗](https://www.youtube.com/watch?v=XhXIHVGCFFM) for more details.

My question here is more around weather there is any solution for this at all?

### Impact
All customers would be impacted. According to our PenTest team its a MEDIUM severity since it requires IOs jailbreaking.

**Comment by NiklasMerz** [comment]
Please don't open security issues as GitHub issues as they are public and can be very bad in certain cases.

If something requires an iOS jailbreak I don't think this is really a problem since a jailbreaked phone is less secure by design.
