### ISSUE TITLE
Fingerprint dialog appears again

### ISSUE THREAD

**Issue by dhivehi** [NiklasMerz/cordova-plugin-fingerprint-aio#48]
How to hide the fingerprint dialog on success?

**Comment by NiklasMerz** [comment]
Are you talking about Android or iOS? The dialog is hidden automatically after success. Which dialog are you talking about in particular? Could you please attach a screenshot?

**Comment by deqe** [comment]
The dialog did not hide after successfully authenticated by "USE BACKUP" in android. Any way to hide the dialog? Thanks.

**Comment by NiklasMerz** [comment]
Sorry for the delay. I will check this soon.

**Comment by NiklasMerz** [comment]
I tried this out. There is no dialog after after the pin entry dialog.

**Comment by vkpbtc** [comment]
This happen to me. Once successful "Use backup" authentication, again finger print authentication dialog is appeared. I think it is in loop.

**Comment by NiklasMerz** [comment]
Ok I will check this out.

@vkpbtc If you have a working solution feel free to submit a pull request.

**Comment by mmbossoni** [comment]
Hi,
I'm facing this problem as well. 
I was reading the documentation and found this.
https://cordova.apache.org/docs/en/latest/guide/platforms/android/plugin.html#launching-other-activities

Maybe the plugin is relaunching the fingerprint dialog when it should not?

**Comment by NiklasMerz** [comment]
Hi everybody. I just checked it and I cannot reproduce this issue.

If you have an example please open the issue again and post it here.
