### ISSUE TITLE
iOS disable backup option

### ISSUE THREAD

**Issue by maxborgatti** [NiklasMerz/cordova-plugin-fingerprint-aio#49]
Hi,

i'm setting disableBackup: true but on iOS this does not matter: on devices without Touch ID (iPhone 5c, iPad mini) every time the pinn/backup prompt shows.

Is this an issue or this won't be an option for iOS?

Thanks in advance for the cooperation on this

**Comment by NiklasMerz** [comment]
Hello

I will habe to check that. At the moment this looks like the intenden behavior. Mybe this should be changed.

But why do you use this function on devices without TouchId anyway. You could solve this issue by checking if fingerprint is availble, couldn´t you?

Thanks for your feedback

**Comment by maxborgatti** [comment]
Oh, my fault!

This does the trick: this.faio.isAvailable().then(()=>{this.faio.show({...

Thanks a lot!

**Comment by NiklasMerz** [comment]
I´m happy to help you.
