### ISSUE TITLE
Face ID

### ISSUE THREAD

**Issue by maxborgatti** [NiklasMerz/cordova-plugin-fingerprint-aio#50]
Question: any update for Apple's iPhone X Face ID?

**Comment by NiklasMerz** [comment]
Great suggestion. I will check the documation for possible APIs

**Comment by NiklasMerz** [comment]
As far as I found information on this FaceId is using the same policy. Maybe it works out of the box.

@maxborgatti You could try that in the new Xcode version.

**Comment by NiklasMerz** [comment]
This needs some testing

**Comment by maxborgatti** [comment]
Are you sure this can be tested on Xcode? Wouldn't be needed a real device for that?

In this last case, as far as i get one, i'll test and feed back

**Comment by NiklasMerz** [comment]
I think the iPhone X simulator supports FaceId testing. Testing with a real device is even better.

Thanks in advance for your feedback.

**Comment by cheng1994** [comment]
I can confirm FaceID works out of the box

**Comment by jamesdixon** [comment]
Well damn, that's cool 👍

**Comment by NiklasMerz** [comment]
See https://github.com/EddyVerbruggen/cordova-plugin-touch-id/pull/35

**Comment by NiklasMerz** [comment]
I did some changes to the `isAvailable` function. I would love to hear feedbayk from iPhone X owners. Currently I am unable to test this by myself.

**Comment by NiklasMerz** [comment]
@iryna-kovalchuk Hi

I just released version v1.3.5. Let me know if you have any problems with this version
