### ISSUE TITLE
IOS - Prevent verify passcode when enter invalid touch ID 3 times

### ISSUE THREAD

**Issue by tranphuongyd** [NiklasMerz/cordova-plugin-fingerprint-aio#51]
Hi,
I have an issue when user enter invalid touch ID in 3 times then the system show the verify passcode .
But I want to prevent this step.
Only verify touch Id.
Can you please help me handle this case?
Thanks

**Comment by NiklasMerz** [comment]
Please try the disableBAckup option as described in READEM. 

see also #49

**Comment by tranphuongyd** [comment]
Thanks @NiklasMerz ,
But this option always equals 'true' (disableBackup: true), so I can see this option only for Android not IOS.
Could you please help me check?

**Comment by NiklasMerz** [comment]
Thank you for spotting that. There is an error in the Readme file. disableBackup is a valid parameter for iOS, too. Please try setting this parameter to true when calling show()

**Comment by NiklasMerz** [comment]
See #38 for an example

**Comment by tranphuongyd** [comment]
Thanks, that has already set is 'true' then the button 'use backup' is disable in both Android and IOS, **BUT** in the IOS after I have entered wrong finger in 3 times the passcode form displayed. So I do not want to show the passcode form in this case. 
That is my expection. Can you please help me?

**Comment by NiklasMerz** [comment]
I need to check this.

@ajnrajeev Maybe you can help since you know the iOS authentication policies very good.

**Comment by ajnrajeev** [comment]
@NiklasMerz, I believe it can be done, do you think disableBackup should disable passcode when touch fails first time and prevent auto-passcode entry after 3 failure attempts, or introduce one more input parameter disablePasscode for this?
I am testing out some changes and it looks promising. Once you confirm, I will create a pull request

**Comment by NiklasMerz** [comment]
I think disableBackup should also disable the password fallback after three failed attempts. This should be the most logical behavior. @ajnrajeev and @tranphuongyd do you agree with me?

@ajnrajeev If you would test this and submit a pull request, I am very gratefull. Remeber it´s [Hacktoberfest](https://hacktoberfest.digitalocean.com/) ;-)

**Comment by ajnrajeev** [comment]
@NiklasMerz, I have created a pull request for this. Please take a look
