### ISSUE TITLE
Detect changed fingerprints

### ISSUE THREAD

**Issue by NiklasMerz** [NiklasMerz/cordova-plugin-fingerprint-aio#58]
Add check for changes in fingerprint settings. Add event to handle changes on apllication levels and add (possibly optional) ways to recover from changed state.

### For iOS:
Save and compare [evaluatedPolicyDomainState](https://developer.apple.com/documentation/localauthentication/lacontext/1514150-evaluatedpolicydomainstate)

### For Android
Handle `KeyPermanentlyInvalidatedException`. The cipher key becomes invalid of security settings where changed. One way to handle this is given in #54 .

**Comment by digaant333** [comment]
Hi , I would like to do this

**Comment by NiklasMerz** [comment]
Hi @digaant333 

This would be very nice. You can find information hwo to contribute in this [file](https://developer.apple.com/documentation/localauthentication/lacontext/1514150-evaluatedpolicydomainstate). If you have any questions, you can contact me on gitter (link description). 

I have a solution please submit a pull request and we cann discuss your code. 

Have fun  :tada:
