### ISSUE TITLE
V1.3.1, portuguese translations not reflecting.

### ISSUE THREAD

**Issue by shivalipawar** [NiklasMerz/cordova-plugin-fingerprint-aio#62]
We have installed latest version in project using command 
`cordova plugin add cordova-plugin-fingerprint-aio@v1.3.1 --save`
then tried running app on device (motog4+, nought) language as portuguese  but translation are not reflecting.
we checked plugins folder , we have translations available for above language

**Comment by NiklasMerz** [comment]
Sorry I forgot to add the new file to the plugin.xml file, again. You could submit an pull request for that.
