### ISSUE TITLE
Plugin not working on iOS >= 9

### ISSUE THREAD

**Issue by ocReaper** [NiklasMerz/cordova-plugin-fingerprint-aio#64]
### What did you do and what did happen?

After installing the plugin and implementing the authentication logic in my application for android the app performed well.

Then testing it on an iOS device: the app loaded the webview but it was totally unresponsive for any kind of actions. Can't tap into inputs nor tap buttons. No scroll also. Almost can't put the app into background. I had to restart the device because it was terribly slow. 

After this failure I've tried it in the simulator and the behaviour was the same.

## Environment

* Plugin version: 1.2.1
* cordova 6.6.1
* ionic 1.7.14
* iOS 10 and 11

## Fixing this bug

After hours of debugging (since I've never seen nor a cordova plugin or swift code earlier) I found that the `isAvailable` function is not utilizing the `iOS >= 9` conditional policy change like the `authenticate` function did.

Also there is an interpolation error in the `authenticate` function's error handling.

Soon I'll send you a PR about this fix.

**Comment by NiklasMerz** [comment]
Thanks for submitting your improvements, but I cannot confirm your changes. Could you please give some details? Which device did you use?

**Comment by ocReaper** [comment]
The device is iPhone 6s with iOS 11.0.3 (15A432)

**Comment by NiklasMerz** [comment]
Strange I never had any issues with an IPhone 6s and iOS 10/11. Maybe your implementation has another issue. Could you please give more details?

**Comment by NiklasMerz** [comment]
closed in #65
