### ISSUE TITLE
Invalid Swift Support - The SwiftSupport folder is missing

### ISSUE THREAD

**Issue by yogeshwar238** [NiklasMerz/cordova-plugin-fingerprint-aio#73]
## Do you have a question ?

I have installed fingerprint aio plugin in our xcode project which is hybrid mobile application for ios. While submitting the ipa file to appstore, It rejects automated validation of ipa. We received mail from apple saying that 
Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it. 

Has anyone faced same issue?
Any help is much appreciated.

## Description

* What did you do?
Installed Cordova fingerprint plugin and its dependent plugin
* What did happen?
Plugin got installed in project successfully. build created without error. But automated validation of ipa getting failed on app store.
* What did you expect to happen?
My mobile app ipa file should be get uploaded and validated successfully on apple app store.
* Type of issue (bug, feature request)
Just need help if anyone has knowledge about this.

## Environment

* Plugin version : 1.2.0
* Build environment (```cordova info```) : cordova v7.0.1
* ```cordova platform ls```: Installed platforms:  ios 4.4.0
* xCode v9.1

**Comment by NiklasMerz** [comment]
Did you use the latest Xcode version from the app store? I had thus issue with a beta version during a release build. The latest store version should work.

**Comment by yogeshwar238** [comment]
As already mentioned, my xCode version is 9.1 (9B55) which recently got updated.
But we faced same issue when xCode version was 8.3 previously.

**Comment by NiklasMerz** [comment]
Ok I have tested the same Xcode build. Which Swift version is set in the Xcode Project build settings?

**Comment by yogeshwar238** [comment]
Swift Language version -> Swift3.2

**Comment by NiklasMerz** [comment]
That version should work. I am afraif I dont know Xcode good enough. Probably there I a build setting which should resolve this. Try searching for general Xcode problems.

**Comment by yogeshwar238** [comment]
Not sure but I have a bit doubt on dependent plugin 'cordova-plugin-add-swift-support' of 'cordova-plugin-fingerprint-aio'. That may causing the issue not adding swift support.

can you suggest alternative plugin which would support fingerprint plugin?

**Comment by NiklasMerz** [comment]
From my experience the Swift support plugin works very well. This plugin adds the necessary settings for swift support at install time of the iOS platform. You could try:

```
cordova platform rm ios
cordova platform add ios
```

This should print logs for adding swift support. You you encounter any errors please let me or the developers of the plugin know.

If you want an alternative plugin this one is very good: https://github.com/EddyVerbruggen/cordova-plugin-touch-id

**Comment by yogeshwar238** [comment]
I meant by alternative plugin is alternative plugin to 'cordova-plugin-add-swift-support' ? not to fingerprint plugin.

Thanks for response. I will check the plugin you suggested.

**Comment by NiklasMerz** [comment]
I don´t think there is an other swift support plugin. 'cordova-plugin-add-swift-support' works great for others and me. I have contributed some changes to this to make it more adjustable. It´s developers are very helpful. Have you created an issue on the 'cordova-plugin-add-swift-support' project?

**Comment by NiklasMerz** [comment]
I am closing this now. If You need any help feel free to contact me on gitter.

**Comment by yangli123456** [comment]
Hi，NiklasMerz, I need your help, while I am uploading IPA to App Store, I am meeting a problem which is "Invalid Swift Support", I have tried many ways but not work, do you know how to solve this ,very thanks.

**Comment by NiklasMerz** [comment]
@yangli123456 Could you please check the Swift version in Xcode buildsettings. For questions feel free to use Gitter](https://gitter.im/cordova-plugin-fingerprint-aio).
