### ISSUE TITLE
Differents returns on Android and iOS

### ISSUE THREAD

**Issue by juniorari** [NiklasMerz/cordova-plugin-fingerprint-aio#75]
Hi Niklas, great plugin, but i have a issue testing your plugin on both platforms.
I noticed who the return of isAvailable() on Android is one string: 'OK'.
But the same method on iOS is another string: 'Available'.
And the result of authentication on both platforms is differents too.
On Android the result is a object with parameter withFingerprint, who returns a string hashed, but on iOS, the return of the method is a string: 'Success'.
Now you can fix it on next versions ;-)

**Comment by NiklasMerz** [comment]
Yes the returned strings are different. Thanks for reminding, I will have a look and possibly make the results more similar.

But anyway the result strings are not very important for using the plugin in most cases. What counts if the error or success callback is called.

**Comment by elsesiy** [comment]
How about changing it to Boolean? I guess nobody is actually evaluating the message anyway :)

**Comment by NiklasMerz** [comment]
Why not :)

**Comment by NiklasMerz** [comment]
Consider faceid and touchid in #50
