### ISSUE TITLE
Android issue when trying to upload pictures 

### ISSUE THREAD

**Issue by mehdyMa** [NiklasMerz/cordova-plugin-fingerprint-aio#79]
Hey Niklas, thank you for this great plugin.
I am trying to upload images from the local library of the device or take a picture using the camera, but on the **Android version**, the fingerprint authentication screen is displayed every time I finish this process which is not reasonable.
So is there any solution for deactivating fingerprint-aio in a specific screen or page ?!!

**Comment by NiklasMerz** [comment]
This sounds like there is a problem in your app logic which displays the login screen. Maybe you trigger "show" in the on resume event.

**Comment by mehdyMa** [comment]
Thank you Niklas for your fast reply,
In fact, I create the lock screen on the resume event :

`  platform.ready().then(() => {
        platform.resume.subscribe(() => {
        let modal = this.modalCtrl.create(LockScreen);
        modal.present();
  }
      });`

And for the LockScreen page: 

`ionViewDidEnter() {
          this.verify();
      }
      verify(){
          this.fingerprint.show(this.fingerprintOptions).then((res) => {
              this.viewCtrl.dismiss();
          }, (err) => {
              console.log(err);
              this.verify();
          });
      }`
 So the lock screen will be displayed every time I leave the app and come again, even if I navigate from the app to the camera or to the gallery, and it's only on Android.

**Comment by NiklasMerz** [comment]
So this works as expected. Maybe you could set an timout to wait a few seconds before you show the fingerprint auth again.

I a m closing this now, because this is a question and not an issue. If you have any questions feel free to use Gitter](https://gitter.im/cordova-plugin-fingerprint-aio).
