### ISSUE TITLE
what does clientSecret do

### ISSUE THREAD

**Issue by crapthings** [NiklasMerz/cordova-plugin-fingerprint-aio#82]
what is this for ?
clientSecret: "password" //Only necessary for Android

**Comment by NiklasMerz** [comment]
Just look in the code ;-)

This is necessary for the keystore encryption.

**Comment by PaoloMessina** [comment]
> Just look in the code ;-)
> 
> This is necessary for the keystore encryption.

I can't find where in code clientSecret is used in Android src, are you sure that this parameters is used for keystore encryption?

Searching in code seems that the plugin manage only this parameters:
disableBackup, title, subtitle, description, fallbackButtonTitle, cancelButtonTitle

**Comment by NiklasMerz** [comment]
This was used in version 2.0.0 and below. Version 3.0 came out a few days ago and this is not necessary anymore.
