### ISSUE TITLE
iOS - Passcode on but touch id off issue

### ISSUE THREAD

**Issue by gintechsystems** [NiklasMerz/cordova-plugin-fingerprint-aio#85]
Hello,

I have tried testing against only having a passcode on but turning off touch id on iOS. It looks like you have the switch handling for biometric type none but are returning finger. I believe this should return none as it is saying there is no biometric available.

Has anyone else had this issue?

**Comment by NiklasMerz** [comment]
If TouchId is turned off the check function should return that. But you are right. If the authentication was done with passcode this should be in the returned value. Have you tried replacing finger in the .none case? If that is the solution feel free to submit a pull request.

**Comment by gintechsystems** [comment]
I was only testing against isAvailable and looked at the source and realized what was going on, but have not tried setting it to none. Are you saying it should be finger and if so why?

I believe you can update canEvaluatePolicy passing LAPolicyDeviceOwnerAuthenticationWithBiometrics (this is the obj-c version of it).

I will try simply changing it to none though if you prefer and see if that works.

Also, great plugin! It has saved me tons of time.

**Comment by NiklasMerz** [comment]
@gintechsystems Did you mean something like this #86 ? Feel free to leave a review or explain what you would like to change.

**Comment by gintechsystems** [comment]
@NiklasMerz Yes, that is exactly what I was talking about. That should resolve the problem and I can work with that.
