### ISSUE TITLE
Error when compiling for cordova android 7.0.0

### ISSUE THREAD

**Issue by remauth** [NiklasMerz/cordova-plugin-fingerprint-aio#87]
## Issue

`cordova build android` fails on a fresh project where only the plugin cordova-plugin-fingerprint-aio has been added:

## Context
- platform: macOS High Sierra
- node: 8.10
- cordova: 8.0.0

## Commands
```
cordova create titi
cd titi
cordova platform add android
cordova plugin add cordova-plugin-fingerprint-aio --save
cordova build android
```

## Error message

```
cp: copyFileSync: could not write to dest file (code=ENOENT):/Users/guillaume/Downloads/titi/platforms/android/res/xml/config.xml

Parsing /Users/guillaume/Downloads/titi/platforms/android/res/xml/config.xml failed
(node:2931) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/guillaume/Downloads/titi/platforms/android/res/xml/config.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.parseElementtreeSync (/Users/guillaume/Downloads/titi/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:180:27)
    at new ConfigParser (/Users/guillaume/Downloads/titi/platforms/android/cordova/node_modules/cordova-common/src/ConfigParser/ConfigParser.js:30:24)
    at updateConfigFilesFrom (/Users/guillaume/Downloads/titi/platforms/android/cordova/lib/prepare.js:106:18)
    at Api.module.exports.prepare (/Users/guillaume/Downloads/titi/platforms/android/cordova/lib/prepare.js:42:20)
    at Api.prepare (/Users/guillaume/Downloads/titi/platforms/android/cordova/Api.js:192:45)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/prepare.js:106:36
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
(node:2931) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2931) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Current config.xml

```
<?xml version='1.0' encoding='utf-8'?>
<widget id="io.cordova.hellocordova" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>HelloCordova</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <plugin name="cordova-plugin-fingerprint-aio" spec="^1.3.4" />
    <engine name="android" spec="^7.0.0" />
</widget>
```

Thanks for helping

**Comment by NiklasMerz** [comment]
This could be a problem with NodeJS 8 and Cordova 8. Can you test older versions?

I think some paths in plugin.xml of this this plugin have to be changed for Cordova 8. Currently I only use this plugin with an older Cordova Android.

**Comment by remauth** [comment]
OK, I will try.
Could you share the Node, Cordova and Android versions you use for your tests?

Thanks

**Comment by NiklasMerz** [comment]
Currnetly I use this for prodution, too.

I will have to look at this issue for newer versions of cordova.

**Comment by danielahampton** [comment]
I have the same error on Node 8.9.4 and Cordova 7.1.0. When I try and build in Android Studio, it throws the following error: 
`AGPBI: {"kind":"error","text":"error: resource drawable/ic_fp_40px (aka [url]:drawable/ic_fp_40px) not found.","sources":[{"file":"/Users/username/Documents/Projects/project/platforms/android/app/src/main/res/layout/fingerprint_dialog_content.xml"}],"original":"","tool":"AAPT"}`

Not sure if this will help with debugging, but wanted to add in what I saw as well

**Comment by wolkerld** [comment]
I also have the same error here. I am using Cordova 7.1.0 and also tried other versions without success.
When I run `npm install --save @ionic-native/fingerprint-aio` and then `ionic cordova build android`, others plugins don't install because of the fingerprint-aio.

**Comment by robertolocal** [comment]
Mesmo problema aqui. As vezes ocorre erro na hora que instala e outras dá erro ao instalar os próximos plugins.

**Comment by robertolocal** [comment]
Same problem here. Has anyone find a workaround?

**Comment by NiklasMerz** [comment]
You could try the change from #89 . The author of the PR @brad and myself have problems with cordova android 7 and other plugin so we stick witch android 6.

**Comment by JiiB** [comment]
## Current workaround 
I downgraded to Cordova version 7.1.0 (from 8.0.0)
`sudo  npm i -g cordova@7.1.0`

I also removed the android platfrom and added it again:
`ionic cordova platform rm android` 
`ionic cordova platform add android@6.4.0`

This worked for me

**Comment by robertolocal** [comment]
@JiiB, this problem only applies to cordova android 7.
@NiklasMerz the PR #89 dit not solve the issue.

This error on _cordova_plugins.js_ appear after install the plugin and try to install anything else, but sometimes the error is related with _AndroidManifest.xml_:
> (node:281) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'ionic_folder/platforms/android/assets/www/cordova_plugins.js'

**Comment by AkashM08** [comment]
Hi,
Even I am facing same issue:

D:\IonicProject\platforms\android\app\src\main\res\layout\fingerprint_dialog_content.xml:37: error: resource drawable/ic_fp_40px (aka io.ionic.starter:drawable/ic_fp_40px) not found.
error: failed linking file resources.

Can you please suggest me on this.

**Comment by NiklasMerz** [comment]
@AkashM08 Could you please give more information about your build environment. Try `cordova info`

**Comment by NiklasMerz** [comment]
Since this is more a question check #92 and #94 for updates on this issue,

**Comment by caribeedu** [comment]
> ## Current workaround
> I downgraded to Cordova version 7.1.0 (from 8.0.0)
> `sudo npm i -g cordova@7.1.0`
> 
> I also removed the android platfrom and added it again:
> `ionic cordova platform rm android`
> `ionic cordova platform add android@6.4.0`
> 
> This worked for me

you a god, saved my life

**Comment by gravyplaya** [comment]
> I have downgraded my platform to Node 6.13.1 and Cordova 7.1.0: It works now!
> Thanks

Node 6 has been deprecated and will no longer work.
