### ISSUE TITLE
isAvailable check if configured or fingerprint reader not existent

### ISSUE THREAD

**Issue by matrixn** [NiklasMerz/cordova-plugin-fingerprint-aio#9]
I've tried to use this plugin but it seems that Fingerprint.isAvailable() method is returning success on non-fingerprint devices which is a failure...

**Comment by NiklasMerz** [comment]
I can confirm this with my phone. I am going to fix this issue

**Comment by NiklasMerz** [comment]
isAvalable will now only return success if the device has fingerprint hardware and authentivation is set up.

@matrixn You can test this with latest version from master. I will publish a new version on npm soon.

**Comment by NiklasMerz** [comment]
Release ob npm with 6219ea9fff5d35b9e84f4795f81f03adb343cfb6

**Comment by kyriediculous** [comment]
@NiklasMerz A different error message for non-fingerprint device vs not set -up but fingerprint device would be nice if possible.

**Comment by NiklasMerz** [comment]
Good point

**Comment by NiklasMerz** [comment]
Done with #131
