### ISSUE TITLE
Not compatible with Cordova 7.0.0

### ISSUE THREAD

**Issue by Limoli** [NiklasMerz/cordova-plugin-fingerprint-aio#95]
## Description

* What did happen?

AndroidManifest has wrong parameters.
android.permission.USE_FINGERPRINT is added as attribute to the application element.

`<application android:hardwareAccelerated="true" android:icon="@mipmap/icon" android:label="@string/app_name" android:name="android.permission.USE_FINGERPRINT" android:supportsRtl="true">`

* Type of issue (bug, feature request)
BUG

## Environment

* Plugin version

4.7.0

* Build environment

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.1.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    ios-sim    : 6.1.2
    Node       : v9.5.0
    npm        : 5.6.0
    OS         : macOS High Sierra
    Xcode      : Xcode 9.3 Build version 9E145

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

Installed platforms:
  

> android 7.1.0

Available platforms:

>   blackberry10 ~3.8.0 (deprecated)
>   browser ~5.0.0
>   ios ~4.5.1
>   osx ~4.0.1
>   ubuntu ~4.3.4 (deprecated)
>   webos ~3.7.0
>   windows ~5.0.0
>   www ^3.12.0
>

**Comment by NiklasMerz** [comment]
See #94 . Please comment on this pr. We are working on Android version problems.
