### ISSUE TITLE
Return finger on iPhone 5 without fingerprint

### ISSUE THREAD

**Issue by robertolocal** [NiklasMerz/cordova-plugin-fingerprint-aio#98]
## Description

* What did you do? Call `isAvailable` function.
* What did happen? Return '_finger_' on iPhone 5 without fingerprint functionality.
* What did you expect to happen? Return '_Not Available_'.
* Type of issue: bug

## Environment

* Plugin version latest: 1.3.6
* Build environment: ios 4.5.4, xcode 9.2, iPhone 5.

**Comment by NiklasMerz** [comment]
Ok that should not happen. Looks like the policy evaluation fails in this case. I will check that.

/cc @elsesiy and @ocReaper You created a PR together changing this. Do you have any comments?

**Comment by robertolocal** [comment]
Is there some workaround that you recommend to fix it or should I disable it on iPhone by now?

**Comment by NiklasMerz** [comment]
Have you tried what happen when you call `show()` on an iPhone 5? This should ask for the device PIN.

**Comment by BassamHabash** [comment]
Hi @NiklasMerz , I have same issue, is there any solution for it ?

**Comment by robertolocal** [comment]
Show function throw "fingerprint unavailable".

**Comment by aniket-pracheta** [comment]
issue yet not resolve facing above issue

**Comment by aniket-pracheta** [comment]
IOS device, not connecting finger print scanner then to function return's "figure" in response also the pin dialog open if you have set pin code to the device

**Comment by NiklasMerz** [comment]
I do not really understand the problem. Could you post some logs or even a screencast of this problem? Are you waiting until the deviceready event fires?

**Comment by aniket-pracheta** [comment]
hii,

When ever i call for IOS

Fingerprint.isAvailable(isAvailableSuccess, isAvailableError);

it always goes in success function that is isAvailableSuccess in which 
it gives response "fingure" even if device do not have touch ID for 
example devices like:-ipad 4 , so this is bug i guess which need to resolve.

Thanks & Regards,
Aniket Pracheta

**Comment by aniket-pracheta** [comment]
yes, I have call function after device gets ready.

**Comment by NiklasMerz** [comment]
Did you try the latest Xcode version? Does authetication work like expected on those devices?

**Comment by gitofchang** [comment]
@NiklasMerz Did you have a chance to solve this issue? It is actually the bug of this plugin. The isAvailable() function returns true, even though iPhone 5 has no fingerprint authentication.

Hoping you will be able to solve this issue soon.

**Comment by NiklasMerz** [comment]
Please test latest the latest release candidate: 

`cordova plugin add cordova-plugin-fingerprint-aio@rc`

**Comment by ruazakharo** [comment]
@NiklasMerz I can't download it.
